/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ChangePwOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChangePwOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChangePwOutput
        //private ChangePwOutput instance;

        public ChangePwOutputTests()
        {
            // TODO uncomment below to create an instance of ChangePwOutput
            //instance = new ChangePwOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChangePwOutput
        /// </summary>
        [Fact]
        public void ChangePwOutputInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChangePwOutput
            //Assert.IsType<ChangePwOutput>(instance);
        }

        /// <summary>
        /// Test the property 'Changed'
        /// </summary>
        [Fact]
        public void ChangedTest()
        {
            // TODO unit test for the property 'Changed'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
