/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ChangePwInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChangePwInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChangePwInput
        //private ChangePwInput instance;

        public ChangePwInputTests()
        {
            // TODO uncomment below to create an instance of ChangePwInput
            //instance = new ChangePwInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChangePwInput
        /// </summary>
        [Fact]
        public void ChangePwInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChangePwInput
            //Assert.IsType<ChangePwInput>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Password1'
        /// </summary>
        [Fact]
        public void Password1Test()
        {
            // TODO unit test for the property 'Password1'
        }

        /// <summary>
        /// Test the property 'Password2'
        /// </summary>
        [Fact]
        public void Password2Test()
        {
            // TODO unit test for the property 'Password2'
        }
    }
}
