/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CheckInOutInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CheckInOutInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CheckInOutInput
        //private CheckInOutInput instance;

        public CheckInOutInputTests()
        {
            // TODO uncomment below to create an instance of CheckInOutInput
            //instance = new CheckInOutInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CheckInOutInput
        /// </summary>
        [Fact]
        public void CheckInOutInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" CheckInOutInput
            //Assert.IsType<CheckInOutInput>(instance);
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }

        /// <summary>
        /// Test the property 'WorkerId'
        /// </summary>
        [Fact]
        public void WorkerIdTest()
        {
            // TODO unit test for the property 'WorkerId'
        }

        /// <summary>
        /// Test the property 'ExtraExpenses'
        /// </summary>
        [Fact]
        public void ExtraExpensesTest()
        {
            // TODO unit test for the property 'ExtraExpenses'
        }

        /// <summary>
        /// Test the property 'HoursDriven'
        /// </summary>
        [Fact]
        public void HoursDrivenTest()
        {
            // TODO unit test for the property 'HoursDriven'
        }

        /// <summary>
        /// Test the property 'MilesDriven'
        /// </summary>
        [Fact]
        public void MilesDrivenTest()
        {
            // TODO unit test for the property 'MilesDriven'
        }

        /// <summary>
        /// Test the property 'MinutesDriven'
        /// </summary>
        [Fact]
        public void MinutesDrivenTest()
        {
            // TODO unit test for the property 'MinutesDriven'
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

        /// <summary>
        /// Test the property 'Signin'
        /// </summary>
        [Fact]
        public void SigninTest()
        {
            // TODO unit test for the property 'Signin'
        }

        /// <summary>
        /// Test the property 'Signout'
        /// </summary>
        [Fact]
        public void SignoutTest()
        {
            // TODO unit test for the property 'Signout'
        }
    }
}
