/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DeactivateInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeactivateInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeactivateInput
        //private DeactivateInput instance;

        public DeactivateInputTests()
        {
            // TODO uncomment below to create an instance of DeactivateInput
            //instance = new DeactivateInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeactivateInput
        /// </summary>
        [Fact]
        public void DeactivateInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeactivateInput
            //Assert.IsType<DeactivateInput>(instance);
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
    }
}
