/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing FullAssignmentData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FullAssignmentDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FullAssignmentData
        //private FullAssignmentData instance;

        public FullAssignmentDataTests()
        {
            // TODO uncomment below to create an instance of FullAssignmentData
            //instance = new FullAssignmentData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FullAssignmentData
        /// </summary>
        [Fact]
        public void FullAssignmentDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" FullAssignmentData
            //Assert.IsType<FullAssignmentData>(instance);
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

        /// <summary>
        /// Test the property 'Extraexpcents'
        /// </summary>
        [Fact]
        public void ExtraexpcentsTest()
        {
            // TODO unit test for the property 'Extraexpcents'
        }

        /// <summary>
        /// Test the property 'HoursDriven'
        /// </summary>
        [Fact]
        public void HoursDrivenTest()
        {
            // TODO unit test for the property 'HoursDriven'
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }

        /// <summary>
        /// Test the property 'JobNotes'
        /// </summary>
        [Fact]
        public void JobNotesTest()
        {
            // TODO unit test for the property 'JobNotes'
        }

        /// <summary>
        /// Test the property 'MilesDriven'
        /// </summary>
        [Fact]
        public void MilesDrivenTest()
        {
            // TODO unit test for the property 'MilesDriven'
        }

        /// <summary>
        /// Test the property 'MinutesDriven'
        /// </summary>
        [Fact]
        public void MinutesDrivenTest()
        {
            // TODO unit test for the property 'MinutesDriven'
        }

        /// <summary>
        /// Test the property 'Servicecode'
        /// </summary>
        [Fact]
        public void ServicecodeTest()
        {
            // TODO unit test for the property 'Servicecode'
        }

        /// <summary>
        /// Test the property 'Sitename'
        /// </summary>
        [Fact]
        public void SitenameTest()
        {
            // TODO unit test for the property 'Sitename'
        }

        /// <summary>
        /// Test the property 'UsingFlatRate'
        /// </summary>
        [Fact]
        public void UsingFlatRateTest()
        {
            // TODO unit test for the property 'UsingFlatRate'
        }

        /// <summary>
        /// Test the property 'WorkerId'
        /// </summary>
        [Fact]
        public void WorkerIdTest()
        {
            // TODO unit test for the property 'WorkerId'
        }

        /// <summary>
        /// Test the property 'WorkerNotes'
        /// </summary>
        [Fact]
        public void WorkerNotesTest()
        {
            // TODO unit test for the property 'WorkerNotes'
        }

        /// <summary>
        /// Test the property 'Workorder'
        /// </summary>
        [Fact]
        public void WorkorderTest()
        {
            // TODO unit test for the property 'Workorder'
        }

        /// <summary>
        /// Test the property 'Signin'
        /// </summary>
        [Fact]
        public void SigninTest()
        {
            // TODO unit test for the property 'Signin'
        }

        /// <summary>
        /// Test the property 'Signout'
        /// </summary>
        [Fact]
        public void SignoutTest()
        {
            // TODO unit test for the property 'Signout'
        }
    }
}
