/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing HomeStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HomeStatsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HomeStats
        //private HomeStats instance;

        public HomeStatsTests()
        {
            // TODO uncomment below to create an instance of HomeStats
            //instance = new HomeStats();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HomeStats
        /// </summary>
        [Fact]
        public void HomeStatsInstanceTest()
        {
            // TODO uncomment below to test "IsType" HomeStats
            //Assert.IsType<HomeStats>(instance);
        }

        /// <summary>
        /// Test the property 'Jobs'
        /// </summary>
        [Fact]
        public void JobsTest()
        {
            // TODO unit test for the property 'Jobs'
        }

        /// <summary>
        /// Test the property 'JobsAvg'
        /// </summary>
        [Fact]
        public void JobsAvgTest()
        {
            // TODO unit test for the property 'JobsAvg'
        }

        /// <summary>
        /// Test the property 'Miles'
        /// </summary>
        [Fact]
        public void MilesTest()
        {
            // TODO unit test for the property 'Miles'
        }

        /// <summary>
        /// Test the property 'MilesAvg'
        /// </summary>
        [Fact]
        public void MilesAvgTest()
        {
            // TODO unit test for the property 'MilesAvg'
        }

        /// <summary>
        /// Test the property 'SiteUrl'
        /// </summary>
        [Fact]
        public void SiteUrlTest()
        {
            // TODO unit test for the property 'SiteUrl'
        }

        /// <summary>
        /// Test the property 'Workers'
        /// </summary>
        [Fact]
        public void WorkersTest()
        {
            // TODO unit test for the property 'Workers'
        }

        /// <summary>
        /// Test the property 'WorkersAvg'
        /// </summary>
        [Fact]
        public void WorkersAvgTest()
        {
            // TODO unit test for the property 'WorkersAvg'
        }
    }
}
