/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing JobAssignment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobAssignmentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobAssignment
        //private JobAssignment instance;

        public JobAssignmentTests()
        {
            // TODO uncomment below to create an instance of JobAssignment
            //instance = new JobAssignment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobAssignment
        /// </summary>
        [Fact]
        public void JobAssignmentInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobAssignment
            //Assert.IsType<JobAssignment>(instance);
        }

        /// <summary>
        /// Test the property 'FlatRate'
        /// </summary>
        [Fact]
        public void FlatRateTest()
        {
            // TODO unit test for the property 'FlatRate'
        }

        /// <summary>
        /// Test the property 'Worker'
        /// </summary>
        [Fact]
        public void WorkerTest()
        {
            // TODO unit test for the property 'Worker'
        }
    }
}
