/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing JobDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobDetailTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobDetail
        //private JobDetail instance;

        public JobDetailTests()
        {
            // TODO uncomment below to create an instance of JobDetail
            //instance = new JobDetail();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobDetail
        /// </summary>
        [Fact]
        public void JobDetailInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobDetail
            //Assert.IsType<JobDetail>(instance);
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

        /// <summary>
        /// Test the property 'Servicecode'
        /// </summary>
        [Fact]
        public void ServicecodeTest()
        {
            // TODO unit test for the property 'Servicecode'
        }

        /// <summary>
        /// Test the property 'Sitename'
        /// </summary>
        [Fact]
        public void SitenameTest()
        {
            // TODO unit test for the property 'Sitename'
        }

        /// <summary>
        /// Test the property 'Workorder'
        /// </summary>
        [Fact]
        public void WorkorderTest()
        {
            // TODO unit test for the property 'Workorder'
        }
    }
}
