/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing JobData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobData
        //private JobData instance;

        public JobDataTests()
        {
            // TODO uncomment below to create an instance of JobData
            //instance = new JobData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobData
        /// </summary>
        [Fact]
        public void JobDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobData
            //Assert.IsType<JobData>(instance);
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }

        /// <summary>
        /// Test the property 'JobName'
        /// </summary>
        [Fact]
        public void JobNameTest()
        {
            // TODO unit test for the property 'JobName'
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

        /// <summary>
        /// Test the property 'ServiceCode'
        /// </summary>
        [Fact]
        public void ServiceCodeTest()
        {
            // TODO unit test for the property 'ServiceCode'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'WorkOrder'
        /// </summary>
        [Fact]
        public void WorkOrderTest()
        {
            // TODO unit test for the property 'WorkOrder'
        }

        /// <summary>
        /// Test the property 'WorkerName'
        /// </summary>
        [Fact]
        public void WorkerNameTest()
        {
            // TODO unit test for the property 'WorkerName'
        }

        /// <summary>
        /// Test the property 'WorkerId'
        /// </summary>
        [Fact]
        public void WorkerIdTest()
        {
            // TODO unit test for the property 'WorkerId'
        }
    }
}
