/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing JobDeleteOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobDeleteOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobDeleteOutput
        //private JobDeleteOutput instance;

        public JobDeleteOutputTests()
        {
            // TODO uncomment below to create an instance of JobDeleteOutput
            //instance = new JobDeleteOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobDeleteOutput
        /// </summary>
        [Fact]
        public void JobDeleteOutputInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobDeleteOutput
            //Assert.IsType<JobDeleteOutput>(instance);
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }
    }
}
