/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing JobEditPageOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobEditPageOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobEditPageOutput
        //private JobEditPageOutput instance;

        public JobEditPageOutputTests()
        {
            // TODO uncomment below to create an instance of JobEditPageOutput
            //instance = new JobEditPageOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobEditPageOutput
        /// </summary>
        [Fact]
        public void JobEditPageOutputInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobEditPageOutput
            //Assert.IsType<JobEditPageOutput>(instance);
        }

        /// <summary>
        /// Test the property 'Workers'
        /// </summary>
        [Fact]
        public void WorkersTest()
        {
            // TODO unit test for the property 'Workers'
        }

        /// <summary>
        /// Test the property 'Job'
        /// </summary>
        [Fact]
        public void JobTest()
        {
            // TODO unit test for the property 'Job'
        }
    }
}
