/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing JobEditInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobEditInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobEditInput
        //private JobEditInput instance;

        public JobEditInputTests()
        {
            // TODO uncomment below to create an instance of JobEditInput
            //instance = new JobEditInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobEditInput
        /// </summary>
        [Fact]
        public void JobEditInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobEditInput
            //Assert.IsType<JobEditInput>(instance);
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'Assignments'
        /// </summary>
        [Fact]
        public void AssignmentsTest()
        {
            // TODO unit test for the property 'Assignments'
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

        /// <summary>
        /// Test the property 'Servcode'
        /// </summary>
        [Fact]
        public void ServcodeTest()
        {
            // TODO unit test for the property 'Servcode'
        }

        /// <summary>
        /// Test the property 'Sitename'
        /// </summary>
        [Fact]
        public void SitenameTest()
        {
            // TODO unit test for the property 'Sitename'
        }

        /// <summary>
        /// Test the property 'Workorder'
        /// </summary>
        [Fact]
        public void WorkorderTest()
        {
            // TODO unit test for the property 'Workorder'
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }
    }
}
