/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing JobListOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobListOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobListOutput
        //private JobListOutput instance;

        public JobListOutputTests()
        {
            // TODO uncomment below to create an instance of JobListOutput
            //instance = new JobListOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobListOutput
        /// </summary>
        [Fact]
        public void JobListOutputInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobListOutput
            //Assert.IsType<JobListOutput>(instance);
        }

        /// <summary>
        /// Test the property 'Admin'
        /// </summary>
        [Fact]
        public void AdminTest()
        {
            // TODO unit test for the property 'Admin'
        }

        /// <summary>
        /// Test the property 'Assigned'
        /// </summary>
        [Fact]
        public void AssignedTest()
        {
            // TODO unit test for the property 'Assigned'
        }

        /// <summary>
        /// Test the property 'Completed'
        /// </summary>
        [Fact]
        public void CompletedTest()
        {
            // TODO unit test for the property 'Completed'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'Jobs'
        /// </summary>
        [Fact]
        public void JobsTest()
        {
            // TODO unit test for the property 'Jobs'
        }

        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }

        /// <summary>
        /// Test the property 'Params'
        /// </summary>
        [Fact]
        public void ParamsTest()
        {
            // TODO unit test for the property 'Params'
        }

        /// <summary>
        /// Test the property 'Started'
        /// </summary>
        [Fact]
        public void StartedTest()
        {
            // TODO unit test for the property 'Started'
        }
    }
}
