/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing LogoutOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LogoutOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LogoutOutput
        //private LogoutOutput instance;

        public LogoutOutputTests()
        {
            // TODO uncomment below to create an instance of LogoutOutput
            //instance = new LogoutOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LogoutOutput
        /// </summary>
        [Fact]
        public void LogoutOutputInstanceTest()
        {
            // TODO uncomment below to test "IsType" LogoutOutput
            //Assert.IsType<LogoutOutput>(instance);
        }

        /// <summary>
        /// Test the property 'LoggedOut'
        /// </summary>
        [Fact]
        public void LoggedOutTest()
        {
            // TODO unit test for the property 'LoggedOut'
        }
    }
}
