/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ResetPwOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResetPwOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResetPwOutput
        //private ResetPwOutput instance;

        public ResetPwOutputTests()
        {
            // TODO uncomment below to create an instance of ResetPwOutput
            //instance = new ResetPwOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResetPwOutput
        /// </summary>
        [Fact]
        public void ResetPwOutputInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResetPwOutput
            //Assert.IsType<ResetPwOutput>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
