/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ResetPwInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResetPwInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResetPwInput
        //private ResetPwInput instance;

        public ResetPwInputTests()
        {
            // TODO uncomment below to create an instance of ResetPwInput
            //instance = new ResetPwInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResetPwInput
        /// </summary>
        [Fact]
        public void ResetPwInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResetPwInput
            //Assert.IsType<ResetPwInput>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
