/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SearchParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchParamsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchParams
        //private SearchParams instance;

        public SearchParamsTests()
        {
            // TODO uncomment below to create an instance of SearchParams
            //instance = new SearchParams();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchParams
        /// </summary>
        [Fact]
        public void SearchParamsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchParams
            //Assert.IsType<SearchParams>(instance);
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'End'
        /// </summary>
        [Fact]
        public void EndTest()
        {
            // TODO unit test for the property 'End'
        }

        /// <summary>
        /// Test the property 'Fieldnotes'
        /// </summary>
        [Fact]
        public void FieldnotesTest()
        {
            // TODO unit test for the property 'Fieldnotes'
        }

        /// <summary>
        /// Test the property 'SiteName'
        /// </summary>
        [Fact]
        public void SiteNameTest()
        {
            // TODO unit test for the property 'SiteName'
        }

        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Fact]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }

        /// <summary>
        /// Test the property 'WorkOrder'
        /// </summary>
        [Fact]
        public void WorkOrderTest()
        {
            // TODO unit test for the property 'WorkOrder'
        }

        /// <summary>
        /// Test the property 'Workers'
        /// </summary>
        [Fact]
        public void WorkersTest()
        {
            // TODO unit test for the property 'Workers'
        }
    }
}
