/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing WDEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WDEntryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WDEntry
        //private WDEntry instance;

        public WDEntryTests()
        {
            // TODO uncomment below to create an instance of WDEntry
            //instance = new WDEntry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WDEntry
        /// </summary>
        [Fact]
        public void WDEntryInstanceTest()
        {
            // TODO uncomment below to test "IsType" WDEntry
            //Assert.IsType<WDEntry>(instance);
        }

        /// <summary>
        /// Test the property 'Completed'
        /// </summary>
        [Fact]
        public void CompletedTest()
        {
            // TODO unit test for the property 'Completed'
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

        /// <summary>
        /// Test the property 'ExtraExpensesDollars'
        /// </summary>
        [Fact]
        public void ExtraExpensesDollarsTest()
        {
            // TODO unit test for the property 'ExtraExpensesDollars'
        }

        /// <summary>
        /// Test the property 'FlatRate'
        /// </summary>
        [Fact]
        public void FlatRateTest()
        {
            // TODO unit test for the property 'FlatRate'
        }

        /// <summary>
        /// Test the property 'HoursDriven'
        /// </summary>
        [Fact]
        public void HoursDrivenTest()
        {
            // TODO unit test for the property 'HoursDriven'
        }

        /// <summary>
        /// Test the property 'HoursWorked'
        /// </summary>
        [Fact]
        public void HoursWorkedTest()
        {
            // TODO unit test for the property 'HoursWorked'
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }

        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }

        /// <summary>
        /// Test the property 'MilesDriven'
        /// </summary>
        [Fact]
        public void MilesDrivenTest()
        {
            // TODO unit test for the property 'MilesDriven'
        }

        /// <summary>
        /// Test the property 'TrueHoursWorked'
        /// </summary>
        [Fact]
        public void TrueHoursWorkedTest()
        {
            // TODO unit test for the property 'TrueHoursWorked'
        }

        /// <summary>
        /// Test the property 'WorkerId'
        /// </summary>
        [Fact]
        public void WorkerIdTest()
        {
            // TODO unit test for the property 'WorkerId'
        }
    }
}
