/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing WorkerSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkerSummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkerSummary
        //private WorkerSummary instance;

        public WorkerSummaryTests()
        {
            // TODO uncomment below to create an instance of WorkerSummary
            //instance = new WorkerSummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkerSummary
        /// </summary>
        [Fact]
        public void WorkerSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkerSummary
            //Assert.IsType<WorkerSummary>(instance);
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'Admin'
        /// </summary>
        [Fact]
        public void AdminTest()
        {
            // TODO unit test for the property 'Admin'
        }

        /// <summary>
        /// Test the property 'Deactivated'
        /// </summary>
        [Fact]
        public void DeactivatedTest()
        {
            // TODO unit test for the property 'Deactivated'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'FlatRateCents'
        /// </summary>
        [Fact]
        public void FlatRateCentsTest()
        {
            // TODO unit test for the property 'FlatRateCents'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'MustChangePw'
        /// </summary>
        [Fact]
        public void MustChangePwTest()
        {
            // TODO unit test for the property 'MustChangePw'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'RateDriveHourlyCents'
        /// </summary>
        [Fact]
        public void RateDriveHourlyCentsTest()
        {
            // TODO unit test for the property 'RateDriveHourlyCents'
        }

        /// <summary>
        /// Test the property 'RateHourlyCents'
        /// </summary>
        [Fact]
        public void RateHourlyCentsTest()
        {
            // TODO unit test for the property 'RateHourlyCents'
        }

        /// <summary>
        /// Test the property 'RateMileageCents'
        /// </summary>
        [Fact]
        public void RateMileageCentsTest()
        {
            // TODO unit test for the property 'RateMileageCents'
        }
    }
}
