/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing WorkerCreateInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkerCreateInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkerCreateInput
        //private WorkerCreateInput instance;

        public WorkerCreateInputTests()
        {
            // TODO uncomment below to create an instance of WorkerCreateInput
            //instance = new WorkerCreateInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkerCreateInput
        /// </summary>
        [Fact]
        public void WorkerCreateInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkerCreateInput
            //Assert.IsType<WorkerCreateInput>(instance);
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'Drivetime'
        /// </summary>
        [Fact]
        public void DrivetimeTest()
        {
            // TODO unit test for the property 'Drivetime'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Flatrate'
        /// </summary>
        [Fact]
        public void FlatrateTest()
        {
            // TODO unit test for the property 'Flatrate'
        }

        /// <summary>
        /// Test the property 'Hourly'
        /// </summary>
        [Fact]
        public void HourlyTest()
        {
            // TODO unit test for the property 'Hourly'
        }

        /// <summary>
        /// Test the property 'Mileage'
        /// </summary>
        [Fact]
        public void MileageTest()
        {
            // TODO unit test for the property 'Mileage'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'Admin'
        /// </summary>
        [Fact]
        public void AdminTest()
        {
            // TODO unit test for the property 'Admin'
        }
    }
}
