/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing WorkerAssignmentInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkerAssignmentInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkerAssignmentInfo
        //private WorkerAssignmentInfo instance;

        public WorkerAssignmentInfoTests()
        {
            // TODO uncomment below to create an instance of WorkerAssignmentInfo
            //instance = new WorkerAssignmentInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkerAssignmentInfo
        /// </summary>
        [Fact]
        public void WorkerAssignmentInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkerAssignmentInfo
            //Assert.IsType<WorkerAssignmentInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Assigned'
        /// </summary>
        [Fact]
        public void AssignedTest()
        {
            // TODO unit test for the property 'Assigned'
        }

        /// <summary>
        /// Test the property 'FlatRate'
        /// </summary>
        [Fact]
        public void FlatRateTest()
        {
            // TODO unit test for the property 'FlatRate'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
