/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing WorkerDataOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkerDataOutputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkerDataOutput
        //private WorkerDataOutput instance;

        public WorkerDataOutputTests()
        {
            // TODO uncomment below to create an instance of WorkerDataOutput
            //instance = new WorkerDataOutput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkerDataOutput
        /// </summary>
        [Fact]
        public void WorkerDataOutputInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkerDataOutput
            //Assert.IsType<WorkerDataOutput>(instance);
        }

        /// <summary>
        /// Test the property 'Entries'
        /// </summary>
        [Fact]
        public void EntriesTest()
        {
            // TODO unit test for the property 'Entries'
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }

        /// <summary>
        /// Test the property 'NumJobs'
        /// </summary>
        [Fact]
        public void NumJobsTest()
        {
            // TODO unit test for the property 'NumJobs'
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

        /// <summary>
        /// Test the property 'Totals'
        /// </summary>
        [Fact]
        public void TotalsTest()
        {
            // TODO unit test for the property 'Totals'
        }
    }
}
