/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Client
{
    /// <summary>
    /// Provides hosting configuration for Org.OpenAPITools
    /// </summary>
    public class HostConfiguration
    {
        private readonly IServiceCollection _services;
        private readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions();

        internal bool HttpClientsAdded { get; private set; }

        /// <summary>
        /// Instantiates the class 
        /// </summary>
        /// <param name="services"></param>
        public HostConfiguration(IServiceCollection services)
        {
            _services = services;
            _jsonOptions.Converters.Add(new JsonStringEnumConverter());
            _jsonOptions.Converters.Add(new DateTimeJsonConverter());
            _jsonOptions.Converters.Add(new DateTimeNullableJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyNullableJsonConverter());
            _jsonOptions.Converters.Add(new ChangePwInputJsonConverter());
            _jsonOptions.Converters.Add(new ChangePwOutputJsonConverter());
            _jsonOptions.Converters.Add(new CheckInOutInputJsonConverter());
            _jsonOptions.Converters.Add(new CheckInOutOutputJsonConverter());
            _jsonOptions.Converters.Add(new DeactivateInputJsonConverter());
            _jsonOptions.Converters.Add(new DeactivateOutputJsonConverter());
            _jsonOptions.Converters.Add(new FullAssignmentDataJsonConverter());
            _jsonOptions.Converters.Add(new HomeStatsJsonConverter());
            _jsonOptions.Converters.Add(new JobAssignmentJsonConverter());
            _jsonOptions.Converters.Add(new JobDataJsonConverter());
            _jsonOptions.Converters.Add(new JobDeleteOutputJsonConverter());
            _jsonOptions.Converters.Add(new JobDetailJsonConverter());
            _jsonOptions.Converters.Add(new JobEditInputJsonConverter());
            _jsonOptions.Converters.Add(new JobEditOutputJsonConverter());
            _jsonOptions.Converters.Add(new JobEditPageOutputJsonConverter());
            _jsonOptions.Converters.Add(new JobListOutputJsonConverter());
            _jsonOptions.Converters.Add(new LoginFormJsonConverter());
            _jsonOptions.Converters.Add(new LoginOutputJsonConverter());
            _jsonOptions.Converters.Add(new LogoutFormJsonConverter());
            _jsonOptions.Converters.Add(new LogoutOutputJsonConverter());
            _jsonOptions.Converters.Add(new LogoutUserOutputJsonConverter());
            _jsonOptions.Converters.Add(new OrderJsonConverter());
            _jsonOptions.Converters.Add(new OrderNullableJsonConverter());
            _jsonOptions.Converters.Add(new ResetPwInputJsonConverter());
            _jsonOptions.Converters.Add(new ResetPwOutputJsonConverter());
            _jsonOptions.Converters.Add(new RestoreInputJsonConverter());
            _jsonOptions.Converters.Add(new RestoreOutputJsonConverter());
            _jsonOptions.Converters.Add(new SearchParamsJsonConverter());
            _jsonOptions.Converters.Add(new StatusJsonConverter());
            _jsonOptions.Converters.Add(new StatusNullableJsonConverter());
            _jsonOptions.Converters.Add(new WDEntryJsonConverter());
            _jsonOptions.Converters.Add(new WorkerAssignmentInfoJsonConverter());
            _jsonOptions.Converters.Add(new WorkerChangeInputJsonConverter());
            _jsonOptions.Converters.Add(new WorkerChangeOutputJsonConverter());
            _jsonOptions.Converters.Add(new WorkerCreateInputJsonConverter());
            _jsonOptions.Converters.Add(new WorkerCreateOutputJsonConverter());
            _jsonOptions.Converters.Add(new WorkerDataOutputJsonConverter());
            _jsonOptions.Converters.Add(new WorkerFilterOptionJsonConverter());
            _jsonOptions.Converters.Add(new WorkerSummaryJsonConverter());
            JsonSerializerOptionsProvider jsonSerializerOptionsProvider = new(_jsonOptions);
            _services.AddSingleton(jsonSerializerOptionsProvider);
            _services.AddSingleton<IApiFactory, ApiFactory>();
            _services.AddSingleton<AdminApiEvents>();
            _services.AddSingleton<UserApiEvents>();
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients(Action<IHttpClientBuilder>? builder = null)
        {
            return AddApiHttpClients((Action<IServiceProvider, HttpClient>?)null, builder);
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients(
            Action<HttpClient>? client,
            Action<IHttpClientBuilder>? builder = null)
        {
            var wrapped = client != null ? new Action<IServiceProvider, HttpClient>((_, httpClient) =>
            {
                client(httpClient);
            }) : null;
            return AddApiHttpClients(wrapped, builder);
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients(
            Action<IServiceProvider, HttpClient>? client,
            Action<IHttpClientBuilder>? builder = null)
        {
            if (client == null)
                client = (_, c) => c.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS);

            List<IHttpClientBuilder> builders = new List<IHttpClientBuilder>();

            builders.Add(_services.AddHttpClient<IAdminApi, AdminApi>("Org.OpenAPITools.Api.IAdminApi", client));
            builders.Add(_services.AddHttpClient<IUserApi, UserApi>("Org.OpenAPITools.Api.IUserApi", client));
            
            if (builder != null)
                foreach (IHttpClientBuilder instance in builders)
                    builder(instance);

            HttpClientsAdded = true;

            return this;
        }

        /// <summary>
        /// Configures the JsonSerializerSettings
        /// </summary>
        /// <param name="options"></param>
        /// <returns></returns>
        public HostConfiguration ConfigureJsonOptions(Action<JsonSerializerOptions> options)
        {
            options(_jsonOptions);

            return this;
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="token"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(TTokenBase token) where TTokenBase : TokenBase
        {
            return AddTokens(new TTokenBase[]{ token });
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="tokens"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(IEnumerable<TTokenBase> tokens) where TTokenBase : TokenBase
        {
            TokenContainer<TTokenBase> container = new TokenContainer<TTokenBase>(tokens);
            _services.AddSingleton(services => container);

            return this;
        }

        /// <summary>
        /// Adds a token provider to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenProvider"></typeparam>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <returns></returns>
        public HostConfiguration UseProvider<TTokenProvider, TTokenBase>() 
            where TTokenProvider : TokenProvider<TTokenBase>
            where TTokenBase : TokenBase
        {
            _services.AddSingleton<TTokenProvider>();
            _services.AddSingleton<TokenProvider<TTokenBase>>(services => services.GetRequiredService<TTokenProvider>());

            return this;
        }
    }
}
