// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Request body shared by the web form and the JSON API for changing a password.
    /// </summary>
    public partial class ChangePwInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChangePwInput" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="password1">password1</param>
        /// <param name="password2">password2</param>
        [JsonConstructor]
        public ChangePwInput(long id, string password1, string password2)
        {
            Id = id;
            Password1 = password1;
            Password2 = password2;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public long Id { get; set; }

        /// <summary>
        /// Gets or Sets Password1
        /// </summary>
        [JsonPropertyName("password1")]
        public string Password1 { get; set; }

        /// <summary>
        /// Gets or Sets Password2
        /// </summary>
        [JsonPropertyName("password2")]
        public string Password2 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChangePwInput {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Password1: ").Append(Password1).Append("\n");
            sb.Append("  Password2: ").Append(Password2).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ChangePwInput" />
    /// </summary>
    public class ChangePwInputJsonConverter : JsonConverter<ChangePwInput>
    {
        /// <summary>
        /// Deserializes json to <see cref="ChangePwInput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ChangePwInput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> id = default;
            Option<string?> password1 = default;
            Option<string?> password2 = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "password1":
                            password1 = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "password2":
                            password2 = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class ChangePwInput.", nameof(id));

            if (!password1.IsSet)
                throw new ArgumentException("Property is required for class ChangePwInput.", nameof(password1));

            if (!password2.IsSet)
                throw new ArgumentException("Property is required for class ChangePwInput.", nameof(password2));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ChangePwInput.");

            if (password1.IsSet && password1.Value == null)
                throw new ArgumentNullException(nameof(password1), "Property is not nullable for class ChangePwInput.");

            if (password2.IsSet && password2.Value == null)
                throw new ArgumentNullException(nameof(password2), "Property is not nullable for class ChangePwInput.");

            return new ChangePwInput(id.Value!.Value!, password1.Value!, password2.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ChangePwInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="changePwInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ChangePwInput changePwInput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, changePwInput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ChangePwInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="changePwInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ChangePwInput changePwInput, JsonSerializerOptions jsonSerializerOptions)
        {
            if (changePwInput.Password1 == null)
                throw new ArgumentNullException(nameof(changePwInput.Password1), "Property is required for class ChangePwInput.");

            if (changePwInput.Password2 == null)
                throw new ArgumentNullException(nameof(changePwInput.Password2), "Property is required for class ChangePwInput.");

            writer.WriteNumber("id", changePwInput.Id);

            writer.WriteString("password1", changePwInput.Password1);

            writer.WriteString("password2", changePwInput.Password2);
        }
    }
}
