// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ChangePwOutput
    /// </summary>
    public partial class ChangePwOutput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChangePwOutput" /> class.
        /// </summary>
        /// <param name="changed">changed</param>
        /// <param name="id">id</param>
        [JsonConstructor]
        public ChangePwOutput(bool changed, long id)
        {
            Changed = changed;
            Id = id;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Changed
        /// </summary>
        [JsonPropertyName("changed")]
        public bool Changed { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public long Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChangePwOutput {\n");
            sb.Append("  Changed: ").Append(Changed).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ChangePwOutput" />
    /// </summary>
    public class ChangePwOutputJsonConverter : JsonConverter<ChangePwOutput>
    {
        /// <summary>
        /// Deserializes json to <see cref="ChangePwOutput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ChangePwOutput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> changed = default;
            Option<long?> id = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "changed":
                            changed = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "id":
                            id = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!changed.IsSet)
                throw new ArgumentException("Property is required for class ChangePwOutput.", nameof(changed));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class ChangePwOutput.", nameof(id));

            if (changed.IsSet && changed.Value == null)
                throw new ArgumentNullException(nameof(changed), "Property is not nullable for class ChangePwOutput.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ChangePwOutput.");

            return new ChangePwOutput(changed.Value!.Value!, id.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ChangePwOutput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="changePwOutput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ChangePwOutput changePwOutput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, changePwOutput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ChangePwOutput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="changePwOutput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ChangePwOutput changePwOutput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteBoolean("changed", changePwOutput.Changed);

            writer.WriteNumber("id", changePwOutput.Id);
        }
    }
}
