// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CheckInOutOutput
    /// </summary>
    public partial class CheckInOutOutput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckInOutOutput" /> class.
        /// </summary>
        /// <param name="jobId">jobId</param>
        /// <param name="workerId">workerId</param>
        [JsonConstructor]
        public CheckInOutOutput(long jobId, long workerId)
        {
            JobId = jobId;
            WorkerId = workerId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets JobId
        /// </summary>
        [JsonPropertyName("job_id")]
        public long JobId { get; set; }

        /// <summary>
        /// Gets or Sets WorkerId
        /// </summary>
        [JsonPropertyName("worker_id")]
        public long WorkerId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CheckInOutOutput {\n");
            sb.Append("  JobId: ").Append(JobId).Append("\n");
            sb.Append("  WorkerId: ").Append(WorkerId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CheckInOutOutput" />
    /// </summary>
    public class CheckInOutOutputJsonConverter : JsonConverter<CheckInOutOutput>
    {
        /// <summary>
        /// Deserializes json to <see cref="CheckInOutOutput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CheckInOutOutput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> jobId = default;
            Option<long?> workerId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "job_id":
                            jobId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "worker_id":
                            workerId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!jobId.IsSet)
                throw new ArgumentException("Property is required for class CheckInOutOutput.", nameof(jobId));

            if (!workerId.IsSet)
                throw new ArgumentException("Property is required for class CheckInOutOutput.", nameof(workerId));

            if (jobId.IsSet && jobId.Value == null)
                throw new ArgumentNullException(nameof(jobId), "Property is not nullable for class CheckInOutOutput.");

            if (workerId.IsSet && workerId.Value == null)
                throw new ArgumentNullException(nameof(workerId), "Property is not nullable for class CheckInOutOutput.");

            return new CheckInOutOutput(jobId.Value!.Value!, workerId.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CheckInOutOutput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="checkInOutOutput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CheckInOutOutput checkInOutOutput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, checkInOutOutput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CheckInOutOutput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="checkInOutOutput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CheckInOutOutput checkInOutOutput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("job_id", checkInOutOutput.JobId);

            writer.WriteNumber("worker_id", checkInOutOutput.WorkerId);
        }
    }
}
