// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// The data needed to update a single worker&#39;s check-in/out record for a job. Used as the request body for both the web form and the JSON API.
    /// </summary>
    public partial class CheckInOutInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckInOutInput" /> class.
        /// </summary>
        /// <param name="jobId">jobId</param>
        /// <param name="workerId">workerId</param>
        /// <param name="extraExpensesCents">extraExpensesCents</param>
        /// <param name="hoursDriven">hoursDriven</param>
        /// <param name="milesDriven">milesDriven</param>
        /// <param name="minutesDriven">minutesDriven</param>
        /// <param name="notes">notes</param>
        /// <param name="signin">signin</param>
        /// <param name="signout">signout</param>
        [JsonConstructor]
        public CheckInOutInput(long jobId, long workerId, Option<long?> extraExpensesCents = default, Option<float?> hoursDriven = default, Option<float?> milesDriven = default, Option<float?> minutesDriven = default, Option<string?> notes = default, Option<string?> signin = default, Option<string?> signout = default)
        {
            JobId = jobId;
            WorkerId = workerId;
            ExtraExpensesCentsOption = extraExpensesCents;
            HoursDrivenOption = hoursDriven;
            MilesDrivenOption = milesDriven;
            MinutesDrivenOption = minutesDriven;
            NotesOption = notes;
            SigninOption = signin;
            SignoutOption = signout;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets JobId
        /// </summary>
        [JsonPropertyName("job_id")]
        public long JobId { get; set; }

        /// <summary>
        /// Gets or Sets WorkerId
        /// </summary>
        [JsonPropertyName("worker_id")]
        public long WorkerId { get; set; }

        /// <summary>
        /// Used to track the state of ExtraExpensesCents
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> ExtraExpensesCentsOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExtraExpensesCents
        /// </summary>
        [JsonPropertyName("extra_expenses_cents")]
        public long? ExtraExpensesCents { get { return this.ExtraExpensesCentsOption.Value; } set { this.ExtraExpensesCentsOption = new(value); } }

        /// <summary>
        /// Used to track the state of HoursDriven
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> HoursDrivenOption { get; private set; }

        /// <summary>
        /// Gets or Sets HoursDriven
        /// </summary>
        [JsonPropertyName("hours_driven")]
        public float? HoursDriven { get { return this.HoursDrivenOption.Value; } set { this.HoursDrivenOption = new(value); } }

        /// <summary>
        /// Used to track the state of MilesDriven
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> MilesDrivenOption { get; private set; }

        /// <summary>
        /// Gets or Sets MilesDriven
        /// </summary>
        [JsonPropertyName("miles_driven")]
        public float? MilesDriven { get { return this.MilesDrivenOption.Value; } set { this.MilesDrivenOption = new(value); } }

        /// <summary>
        /// Used to track the state of MinutesDriven
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> MinutesDrivenOption { get; private set; }

        /// <summary>
        /// Gets or Sets MinutesDriven
        /// </summary>
        [JsonPropertyName("minutes_driven")]
        public float? MinutesDriven { get { return this.MinutesDrivenOption.Value; } set { this.MinutesDrivenOption = new(value); } }

        /// <summary>
        /// Used to track the state of Notes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NotesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        [JsonPropertyName("notes")]
        public string? Notes { get { return this.NotesOption.Value; } set { this.NotesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Signin
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SigninOption { get; private set; }

        /// <summary>
        /// Gets or Sets Signin
        /// </summary>
        [JsonPropertyName("signin")]
        public string? Signin { get { return this.SigninOption.Value; } set { this.SigninOption = new(value); } }

        /// <summary>
        /// Used to track the state of Signout
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SignoutOption { get; private set; }

        /// <summary>
        /// Gets or Sets Signout
        /// </summary>
        [JsonPropertyName("signout")]
        public string? Signout { get { return this.SignoutOption.Value; } set { this.SignoutOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CheckInOutInput {\n");
            sb.Append("  JobId: ").Append(JobId).Append("\n");
            sb.Append("  WorkerId: ").Append(WorkerId).Append("\n");
            sb.Append("  ExtraExpensesCents: ").Append(ExtraExpensesCents).Append("\n");
            sb.Append("  HoursDriven: ").Append(HoursDriven).Append("\n");
            sb.Append("  MilesDriven: ").Append(MilesDriven).Append("\n");
            sb.Append("  MinutesDriven: ").Append(MinutesDriven).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  Signin: ").Append(Signin).Append("\n");
            sb.Append("  Signout: ").Append(Signout).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CheckInOutInput" />
    /// </summary>
    public class CheckInOutInputJsonConverter : JsonConverter<CheckInOutInput>
    {
        /// <summary>
        /// Deserializes json to <see cref="CheckInOutInput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CheckInOutInput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> jobId = default;
            Option<long?> workerId = default;
            Option<long?> extraExpensesCents = default;
            Option<float?> hoursDriven = default;
            Option<float?> milesDriven = default;
            Option<float?> minutesDriven = default;
            Option<string?> notes = default;
            Option<string?> signin = default;
            Option<string?> signout = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "job_id":
                            jobId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "worker_id":
                            workerId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "extra_expenses_cents":
                            extraExpensesCents = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "hours_driven":
                            hoursDriven = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "miles_driven":
                            milesDriven = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "minutes_driven":
                            minutesDriven = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "notes":
                            notes = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "signin":
                            signin = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "signout":
                            signout = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!jobId.IsSet)
                throw new ArgumentException("Property is required for class CheckInOutInput.", nameof(jobId));

            if (!workerId.IsSet)
                throw new ArgumentException("Property is required for class CheckInOutInput.", nameof(workerId));

            if (jobId.IsSet && jobId.Value == null)
                throw new ArgumentNullException(nameof(jobId), "Property is not nullable for class CheckInOutInput.");

            if (workerId.IsSet && workerId.Value == null)
                throw new ArgumentNullException(nameof(workerId), "Property is not nullable for class CheckInOutInput.");

            return new CheckInOutInput(jobId.Value!.Value!, workerId.Value!.Value!, extraExpensesCents, hoursDriven, milesDriven, minutesDriven, notes, signin, signout);
        }

        /// <summary>
        /// Serializes a <see cref="CheckInOutInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="checkInOutInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CheckInOutInput checkInOutInput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, checkInOutInput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CheckInOutInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="checkInOutInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CheckInOutInput checkInOutInput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("job_id", checkInOutInput.JobId);

            writer.WriteNumber("worker_id", checkInOutInput.WorkerId);

            if (checkInOutInput.ExtraExpensesCentsOption.IsSet)
                if (checkInOutInput.ExtraExpensesCentsOption.Value != null)
                    writer.WriteNumber("extra_expenses_cents", checkInOutInput.ExtraExpensesCentsOption.Value!.Value);
                else
                    writer.WriteNull("extra_expenses_cents");

            if (checkInOutInput.HoursDrivenOption.IsSet)
                if (checkInOutInput.HoursDrivenOption.Value != null)
                    writer.WriteNumber("hours_driven", checkInOutInput.HoursDrivenOption.Value!.Value);
                else
                    writer.WriteNull("hours_driven");

            if (checkInOutInput.MilesDrivenOption.IsSet)
                if (checkInOutInput.MilesDrivenOption.Value != null)
                    writer.WriteNumber("miles_driven", checkInOutInput.MilesDrivenOption.Value!.Value);
                else
                    writer.WriteNull("miles_driven");

            if (checkInOutInput.MinutesDrivenOption.IsSet)
                if (checkInOutInput.MinutesDrivenOption.Value != null)
                    writer.WriteNumber("minutes_driven", checkInOutInput.MinutesDrivenOption.Value!.Value);
                else
                    writer.WriteNull("minutes_driven");

            if (checkInOutInput.NotesOption.IsSet)
                if (checkInOutInput.NotesOption.Value != null)
                    writer.WriteString("notes", checkInOutInput.Notes);
                else
                    writer.WriteNull("notes");

            if (checkInOutInput.SigninOption.IsSet)
                if (checkInOutInput.SigninOption.Value != null)
                    writer.WriteString("signin", checkInOutInput.Signin);
                else
                    writer.WriteNull("signin");

            if (checkInOutInput.SignoutOption.IsSet)
                if (checkInOutInput.SignoutOption.Value != null)
                    writer.WriteString("signout", checkInOutInput.Signout);
                else
                    writer.WriteNull("signout");
        }
    }
}
