// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// FullAssignmentData
    /// </summary>
    public partial class FullAssignmentData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FullAssignmentData" /> class.
        /// </summary>
        /// <param name="address">address</param>
        /// <param name="date">date</param>
        /// <param name="extraexpcents">extraexpcents</param>
        /// <param name="hoursDriven">hoursDriven</param>
        /// <param name="jobId">jobId</param>
        /// <param name="jobNotes">jobNotes</param>
        /// <param name="milesDriven">milesDriven</param>
        /// <param name="minutesDriven">minutesDriven</param>
        /// <param name="servicecode">servicecode</param>
        /// <param name="sitename">sitename</param>
        /// <param name="usingFlatRate">usingFlatRate</param>
        /// <param name="workerId">workerId</param>
        /// <param name="workerNotes">workerNotes</param>
        /// <param name="workorder">workorder</param>
        /// <param name="signin">signin</param>
        /// <param name="signout">signout</param>
        [JsonConstructor]
        public FullAssignmentData(string address, DateOnly date, long extraexpcents, float hoursDriven, long jobId, string jobNotes, float milesDriven, float minutesDriven, string servicecode, string sitename, bool usingFlatRate, long workerId, string workerNotes, string workorder, Option<string?> signin = default, Option<string?> signout = default)
        {
            Address = address;
            Date = date;
            Extraexpcents = extraexpcents;
            HoursDriven = hoursDriven;
            JobId = jobId;
            JobNotes = jobNotes;
            MilesDriven = milesDriven;
            MinutesDriven = minutesDriven;
            Servicecode = servicecode;
            Sitename = sitename;
            UsingFlatRate = usingFlatRate;
            WorkerId = workerId;
            WorkerNotes = workerNotes;
            Workorder = workorder;
            SigninOption = signin;
            SignoutOption = signout;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [JsonPropertyName("address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [JsonPropertyName("date")]
        public DateOnly Date { get; set; }

        /// <summary>
        /// Gets or Sets Extraexpcents
        /// </summary>
        [JsonPropertyName("extraexpcents")]
        public long Extraexpcents { get; set; }

        /// <summary>
        /// Gets or Sets HoursDriven
        /// </summary>
        [JsonPropertyName("hours_driven")]
        public float HoursDriven { get; set; }

        /// <summary>
        /// Gets or Sets JobId
        /// </summary>
        [JsonPropertyName("job_id")]
        public long JobId { get; set; }

        /// <summary>
        /// Gets or Sets JobNotes
        /// </summary>
        [JsonPropertyName("job_notes")]
        public string JobNotes { get; set; }

        /// <summary>
        /// Gets or Sets MilesDriven
        /// </summary>
        [JsonPropertyName("miles_driven")]
        public float MilesDriven { get; set; }

        /// <summary>
        /// Gets or Sets MinutesDriven
        /// </summary>
        [JsonPropertyName("minutes_driven")]
        public float MinutesDriven { get; set; }

        /// <summary>
        /// Gets or Sets Servicecode
        /// </summary>
        [JsonPropertyName("servicecode")]
        public string Servicecode { get; set; }

        /// <summary>
        /// Gets or Sets Sitename
        /// </summary>
        [JsonPropertyName("sitename")]
        public string Sitename { get; set; }

        /// <summary>
        /// Gets or Sets UsingFlatRate
        /// </summary>
        [JsonPropertyName("using_flat_rate")]
        public bool UsingFlatRate { get; set; }

        /// <summary>
        /// Gets or Sets WorkerId
        /// </summary>
        [JsonPropertyName("worker_id")]
        public long WorkerId { get; set; }

        /// <summary>
        /// Gets or Sets WorkerNotes
        /// </summary>
        [JsonPropertyName("worker_notes")]
        public string WorkerNotes { get; set; }

        /// <summary>
        /// Gets or Sets Workorder
        /// </summary>
        [JsonPropertyName("workorder")]
        public string Workorder { get; set; }

        /// <summary>
        /// Used to track the state of Signin
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SigninOption { get; private set; }

        /// <summary>
        /// Gets or Sets Signin
        /// </summary>
        [JsonPropertyName("signin")]
        public string? Signin { get { return this.SigninOption.Value; } set { this.SigninOption = new(value); } }

        /// <summary>
        /// Used to track the state of Signout
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SignoutOption { get; private set; }

        /// <summary>
        /// Gets or Sets Signout
        /// </summary>
        [JsonPropertyName("signout")]
        public string? Signout { get { return this.SignoutOption.Value; } set { this.SignoutOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FullAssignmentData {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  Extraexpcents: ").Append(Extraexpcents).Append("\n");
            sb.Append("  HoursDriven: ").Append(HoursDriven).Append("\n");
            sb.Append("  JobId: ").Append(JobId).Append("\n");
            sb.Append("  JobNotes: ").Append(JobNotes).Append("\n");
            sb.Append("  MilesDriven: ").Append(MilesDriven).Append("\n");
            sb.Append("  MinutesDriven: ").Append(MinutesDriven).Append("\n");
            sb.Append("  Servicecode: ").Append(Servicecode).Append("\n");
            sb.Append("  Sitename: ").Append(Sitename).Append("\n");
            sb.Append("  UsingFlatRate: ").Append(UsingFlatRate).Append("\n");
            sb.Append("  WorkerId: ").Append(WorkerId).Append("\n");
            sb.Append("  WorkerNotes: ").Append(WorkerNotes).Append("\n");
            sb.Append("  Workorder: ").Append(Workorder).Append("\n");
            sb.Append("  Signin: ").Append(Signin).Append("\n");
            sb.Append("  Signout: ").Append(Signout).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FullAssignmentData" />
    /// </summary>
    public class FullAssignmentDataJsonConverter : JsonConverter<FullAssignmentData>
    {
        /// <summary>
        /// The format to use to serialize Date
        /// </summary>
        public static string DateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="FullAssignmentData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override FullAssignmentData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> address = default;
            Option<DateOnly?> date = default;
            Option<long?> extraexpcents = default;
            Option<float?> hoursDriven = default;
            Option<long?> jobId = default;
            Option<string?> jobNotes = default;
            Option<float?> milesDriven = default;
            Option<float?> minutesDriven = default;
            Option<string?> servicecode = default;
            Option<string?> sitename = default;
            Option<bool?> usingFlatRate = default;
            Option<long?> workerId = default;
            Option<string?> workerNotes = default;
            Option<string?> workorder = default;
            Option<string?> signin = default;
            Option<string?> signout = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "address":
                            address = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "date":
                            date = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "extraexpcents":
                            extraexpcents = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "hours_driven":
                            hoursDriven = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "job_id":
                            jobId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "job_notes":
                            jobNotes = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "miles_driven":
                            milesDriven = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "minutes_driven":
                            minutesDriven = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "servicecode":
                            servicecode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sitename":
                            sitename = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "using_flat_rate":
                            usingFlatRate = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "worker_id":
                            workerId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "worker_notes":
                            workerNotes = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "workorder":
                            workorder = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "signin":
                            signin = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "signout":
                            signout = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!address.IsSet)
                throw new ArgumentException("Property is required for class FullAssignmentData.", nameof(address));

            if (!date.IsSet)
                throw new ArgumentException("Property is required for class FullAssignmentData.", nameof(date));

            if (!extraexpcents.IsSet)
                throw new ArgumentException("Property is required for class FullAssignmentData.", nameof(extraexpcents));

            if (!hoursDriven.IsSet)
                throw new ArgumentException("Property is required for class FullAssignmentData.", nameof(hoursDriven));

            if (!jobId.IsSet)
                throw new ArgumentException("Property is required for class FullAssignmentData.", nameof(jobId));

            if (!jobNotes.IsSet)
                throw new ArgumentException("Property is required for class FullAssignmentData.", nameof(jobNotes));

            if (!milesDriven.IsSet)
                throw new ArgumentException("Property is required for class FullAssignmentData.", nameof(milesDriven));

            if (!minutesDriven.IsSet)
                throw new ArgumentException("Property is required for class FullAssignmentData.", nameof(minutesDriven));

            if (!servicecode.IsSet)
                throw new ArgumentException("Property is required for class FullAssignmentData.", nameof(servicecode));

            if (!sitename.IsSet)
                throw new ArgumentException("Property is required for class FullAssignmentData.", nameof(sitename));

            if (!usingFlatRate.IsSet)
                throw new ArgumentException("Property is required for class FullAssignmentData.", nameof(usingFlatRate));

            if (!workerId.IsSet)
                throw new ArgumentException("Property is required for class FullAssignmentData.", nameof(workerId));

            if (!workerNotes.IsSet)
                throw new ArgumentException("Property is required for class FullAssignmentData.", nameof(workerNotes));

            if (!workorder.IsSet)
                throw new ArgumentException("Property is required for class FullAssignmentData.", nameof(workorder));

            if (address.IsSet && address.Value == null)
                throw new ArgumentNullException(nameof(address), "Property is not nullable for class FullAssignmentData.");

            if (date.IsSet && date.Value == null)
                throw new ArgumentNullException(nameof(date), "Property is not nullable for class FullAssignmentData.");

            if (extraexpcents.IsSet && extraexpcents.Value == null)
                throw new ArgumentNullException(nameof(extraexpcents), "Property is not nullable for class FullAssignmentData.");

            if (hoursDriven.IsSet && hoursDriven.Value == null)
                throw new ArgumentNullException(nameof(hoursDriven), "Property is not nullable for class FullAssignmentData.");

            if (jobId.IsSet && jobId.Value == null)
                throw new ArgumentNullException(nameof(jobId), "Property is not nullable for class FullAssignmentData.");

            if (jobNotes.IsSet && jobNotes.Value == null)
                throw new ArgumentNullException(nameof(jobNotes), "Property is not nullable for class FullAssignmentData.");

            if (milesDriven.IsSet && milesDriven.Value == null)
                throw new ArgumentNullException(nameof(milesDriven), "Property is not nullable for class FullAssignmentData.");

            if (minutesDriven.IsSet && minutesDriven.Value == null)
                throw new ArgumentNullException(nameof(minutesDriven), "Property is not nullable for class FullAssignmentData.");

            if (servicecode.IsSet && servicecode.Value == null)
                throw new ArgumentNullException(nameof(servicecode), "Property is not nullable for class FullAssignmentData.");

            if (sitename.IsSet && sitename.Value == null)
                throw new ArgumentNullException(nameof(sitename), "Property is not nullable for class FullAssignmentData.");

            if (usingFlatRate.IsSet && usingFlatRate.Value == null)
                throw new ArgumentNullException(nameof(usingFlatRate), "Property is not nullable for class FullAssignmentData.");

            if (workerId.IsSet && workerId.Value == null)
                throw new ArgumentNullException(nameof(workerId), "Property is not nullable for class FullAssignmentData.");

            if (workerNotes.IsSet && workerNotes.Value == null)
                throw new ArgumentNullException(nameof(workerNotes), "Property is not nullable for class FullAssignmentData.");

            if (workorder.IsSet && workorder.Value == null)
                throw new ArgumentNullException(nameof(workorder), "Property is not nullable for class FullAssignmentData.");

            return new FullAssignmentData(address.Value!, date.Value!.Value!, extraexpcents.Value!.Value!, hoursDriven.Value!.Value!, jobId.Value!.Value!, jobNotes.Value!, milesDriven.Value!.Value!, minutesDriven.Value!.Value!, servicecode.Value!, sitename.Value!, usingFlatRate.Value!.Value!, workerId.Value!.Value!, workerNotes.Value!, workorder.Value!, signin, signout);
        }

        /// <summary>
        /// Serializes a <see cref="FullAssignmentData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fullAssignmentData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, FullAssignmentData fullAssignmentData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, fullAssignmentData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="FullAssignmentData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fullAssignmentData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, FullAssignmentData fullAssignmentData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (fullAssignmentData.Address == null)
                throw new ArgumentNullException(nameof(fullAssignmentData.Address), "Property is required for class FullAssignmentData.");

            if (fullAssignmentData.JobNotes == null)
                throw new ArgumentNullException(nameof(fullAssignmentData.JobNotes), "Property is required for class FullAssignmentData.");

            if (fullAssignmentData.Servicecode == null)
                throw new ArgumentNullException(nameof(fullAssignmentData.Servicecode), "Property is required for class FullAssignmentData.");

            if (fullAssignmentData.Sitename == null)
                throw new ArgumentNullException(nameof(fullAssignmentData.Sitename), "Property is required for class FullAssignmentData.");

            if (fullAssignmentData.WorkerNotes == null)
                throw new ArgumentNullException(nameof(fullAssignmentData.WorkerNotes), "Property is required for class FullAssignmentData.");

            if (fullAssignmentData.Workorder == null)
                throw new ArgumentNullException(nameof(fullAssignmentData.Workorder), "Property is required for class FullAssignmentData.");

            writer.WriteString("address", fullAssignmentData.Address);

            writer.WriteString("date", fullAssignmentData.Date.ToString(DateFormat));

            writer.WriteNumber("extraexpcents", fullAssignmentData.Extraexpcents);

            writer.WriteNumber("hours_driven", fullAssignmentData.HoursDriven);

            writer.WriteNumber("job_id", fullAssignmentData.JobId);

            writer.WriteString("job_notes", fullAssignmentData.JobNotes);

            writer.WriteNumber("miles_driven", fullAssignmentData.MilesDriven);

            writer.WriteNumber("minutes_driven", fullAssignmentData.MinutesDriven);

            writer.WriteString("servicecode", fullAssignmentData.Servicecode);

            writer.WriteString("sitename", fullAssignmentData.Sitename);

            writer.WriteBoolean("using_flat_rate", fullAssignmentData.UsingFlatRate);

            writer.WriteNumber("worker_id", fullAssignmentData.WorkerId);

            writer.WriteString("worker_notes", fullAssignmentData.WorkerNotes);

            writer.WriteString("workorder", fullAssignmentData.Workorder);

            if (fullAssignmentData.SigninOption.IsSet)
                if (fullAssignmentData.SigninOption.Value != null)
                    writer.WriteString("signin", fullAssignmentData.Signin);
                else
                    writer.WriteNull("signin");

            if (fullAssignmentData.SignoutOption.IsSet)
                if (fullAssignmentData.SignoutOption.Value != null)
                    writer.WriteString("signout", fullAssignmentData.Signout);
                else
                    writer.WriteNull("signout");
        }
    }
}
