// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// The summary statistics shown on the homepage: total jobs/miles/workers tracked, and a few rough daily/monthly averages. This is public information (shown to logged-out visitors too), so unlike most of the other &#x60;/api/v1/_*&#x60; endpoints, this one requires no authentication.
    /// </summary>
    public partial class HomeStats : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HomeStats" /> class.
        /// </summary>
        /// <param name="jobs">jobs</param>
        /// <param name="jobsAvg">jobsAvg</param>
        /// <param name="miles">miles</param>
        /// <param name="milesAvg">milesAvg</param>
        /// <param name="siteUrl">siteUrl</param>
        /// <param name="workers">workers</param>
        /// <param name="workersAvg">workersAvg</param>
        [JsonConstructor]
        public HomeStats(long jobs, string jobsAvg, string miles, string milesAvg, string siteUrl, long workers, string workersAvg)
        {
            Jobs = jobs;
            JobsAvg = jobsAvg;
            Miles = miles;
            MilesAvg = milesAvg;
            SiteUrl = siteUrl;
            Workers = workers;
            WorkersAvg = workersAvg;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Jobs
        /// </summary>
        [JsonPropertyName("jobs")]
        public long Jobs { get; set; }

        /// <summary>
        /// Gets or Sets JobsAvg
        /// </summary>
        [JsonPropertyName("jobs_avg")]
        public string JobsAvg { get; set; }

        /// <summary>
        /// Gets or Sets Miles
        /// </summary>
        [JsonPropertyName("miles")]
        public string Miles { get; set; }

        /// <summary>
        /// Gets or Sets MilesAvg
        /// </summary>
        [JsonPropertyName("miles_avg")]
        public string MilesAvg { get; set; }

        /// <summary>
        /// Gets or Sets SiteUrl
        /// </summary>
        [JsonPropertyName("site_url")]
        public string SiteUrl { get; set; }

        /// <summary>
        /// Gets or Sets Workers
        /// </summary>
        [JsonPropertyName("workers")]
        public long Workers { get; set; }

        /// <summary>
        /// Gets or Sets WorkersAvg
        /// </summary>
        [JsonPropertyName("workers_avg")]
        public string WorkersAvg { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HomeStats {\n");
            sb.Append("  Jobs: ").Append(Jobs).Append("\n");
            sb.Append("  JobsAvg: ").Append(JobsAvg).Append("\n");
            sb.Append("  Miles: ").Append(Miles).Append("\n");
            sb.Append("  MilesAvg: ").Append(MilesAvg).Append("\n");
            sb.Append("  SiteUrl: ").Append(SiteUrl).Append("\n");
            sb.Append("  Workers: ").Append(Workers).Append("\n");
            sb.Append("  WorkersAvg: ").Append(WorkersAvg).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HomeStats" />
    /// </summary>
    public class HomeStatsJsonConverter : JsonConverter<HomeStats>
    {
        /// <summary>
        /// Deserializes json to <see cref="HomeStats" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override HomeStats Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> jobs = default;
            Option<string?> jobsAvg = default;
            Option<string?> miles = default;
            Option<string?> milesAvg = default;
            Option<string?> siteUrl = default;
            Option<long?> workers = default;
            Option<string?> workersAvg = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "jobs":
                            jobs = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "jobs_avg":
                            jobsAvg = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "miles":
                            miles = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "miles_avg":
                            milesAvg = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "site_url":
                            siteUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "workers":
                            workers = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "workers_avg":
                            workersAvg = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!jobs.IsSet)
                throw new ArgumentException("Property is required for class HomeStats.", nameof(jobs));

            if (!jobsAvg.IsSet)
                throw new ArgumentException("Property is required for class HomeStats.", nameof(jobsAvg));

            if (!miles.IsSet)
                throw new ArgumentException("Property is required for class HomeStats.", nameof(miles));

            if (!milesAvg.IsSet)
                throw new ArgumentException("Property is required for class HomeStats.", nameof(milesAvg));

            if (!siteUrl.IsSet)
                throw new ArgumentException("Property is required for class HomeStats.", nameof(siteUrl));

            if (!workers.IsSet)
                throw new ArgumentException("Property is required for class HomeStats.", nameof(workers));

            if (!workersAvg.IsSet)
                throw new ArgumentException("Property is required for class HomeStats.", nameof(workersAvg));

            if (jobs.IsSet && jobs.Value == null)
                throw new ArgumentNullException(nameof(jobs), "Property is not nullable for class HomeStats.");

            if (jobsAvg.IsSet && jobsAvg.Value == null)
                throw new ArgumentNullException(nameof(jobsAvg), "Property is not nullable for class HomeStats.");

            if (miles.IsSet && miles.Value == null)
                throw new ArgumentNullException(nameof(miles), "Property is not nullable for class HomeStats.");

            if (milesAvg.IsSet && milesAvg.Value == null)
                throw new ArgumentNullException(nameof(milesAvg), "Property is not nullable for class HomeStats.");

            if (siteUrl.IsSet && siteUrl.Value == null)
                throw new ArgumentNullException(nameof(siteUrl), "Property is not nullable for class HomeStats.");

            if (workers.IsSet && workers.Value == null)
                throw new ArgumentNullException(nameof(workers), "Property is not nullable for class HomeStats.");

            if (workersAvg.IsSet && workersAvg.Value == null)
                throw new ArgumentNullException(nameof(workersAvg), "Property is not nullable for class HomeStats.");

            return new HomeStats(jobs.Value!.Value!, jobsAvg.Value!, miles.Value!, milesAvg.Value!, siteUrl.Value!, workers.Value!.Value!, workersAvg.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="HomeStats" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="homeStats"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, HomeStats homeStats, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, homeStats, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="HomeStats" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="homeStats"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, HomeStats homeStats, JsonSerializerOptions jsonSerializerOptions)
        {
            if (homeStats.JobsAvg == null)
                throw new ArgumentNullException(nameof(homeStats.JobsAvg), "Property is required for class HomeStats.");

            if (homeStats.Miles == null)
                throw new ArgumentNullException(nameof(homeStats.Miles), "Property is required for class HomeStats.");

            if (homeStats.MilesAvg == null)
                throw new ArgumentNullException(nameof(homeStats.MilesAvg), "Property is required for class HomeStats.");

            if (homeStats.SiteUrl == null)
                throw new ArgumentNullException(nameof(homeStats.SiteUrl), "Property is required for class HomeStats.");

            if (homeStats.WorkersAvg == null)
                throw new ArgumentNullException(nameof(homeStats.WorkersAvg), "Property is required for class HomeStats.");

            writer.WriteNumber("jobs", homeStats.Jobs);

            writer.WriteString("jobs_avg", homeStats.JobsAvg);

            writer.WriteString("miles", homeStats.Miles);

            writer.WriteString("miles_avg", homeStats.MilesAvg);

            writer.WriteString("site_url", homeStats.SiteUrl);

            writer.WriteNumber("workers", homeStats.Workers);

            writer.WriteString("workers_avg", homeStats.WorkersAvg);
        }
    }
}
