// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// A single worker assignment on a job, and whether that worker is being paid a flat rate for it.
    /// </summary>
    public partial class JobAssignment : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JobAssignment" /> class.
        /// </summary>
        /// <param name="flatRate">flatRate</param>
        /// <param name="worker">worker</param>
        [JsonConstructor]
        public JobAssignment(bool flatRate, long worker)
        {
            FlatRate = flatRate;
            Worker = worker;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets FlatRate
        /// </summary>
        [JsonPropertyName("flat_rate")]
        public bool FlatRate { get; set; }

        /// <summary>
        /// Gets or Sets Worker
        /// </summary>
        [JsonPropertyName("worker")]
        public long Worker { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JobAssignment {\n");
            sb.Append("  FlatRate: ").Append(FlatRate).Append("\n");
            sb.Append("  Worker: ").Append(Worker).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="JobAssignment" />
    /// </summary>
    public class JobAssignmentJsonConverter : JsonConverter<JobAssignment>
    {
        /// <summary>
        /// Deserializes json to <see cref="JobAssignment" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override JobAssignment Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> flatRate = default;
            Option<long?> worker = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "flat_rate":
                            flatRate = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "worker":
                            worker = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!flatRate.IsSet)
                throw new ArgumentException("Property is required for class JobAssignment.", nameof(flatRate));

            if (!worker.IsSet)
                throw new ArgumentException("Property is required for class JobAssignment.", nameof(worker));

            if (flatRate.IsSet && flatRate.Value == null)
                throw new ArgumentNullException(nameof(flatRate), "Property is not nullable for class JobAssignment.");

            if (worker.IsSet && worker.Value == null)
                throw new ArgumentNullException(nameof(worker), "Property is not nullable for class JobAssignment.");

            return new JobAssignment(flatRate.Value!.Value!, worker.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="JobAssignment" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobAssignment"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, JobAssignment jobAssignment, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, jobAssignment, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="JobAssignment" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobAssignment"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, JobAssignment jobAssignment, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteBoolean("flat_rate", jobAssignment.FlatRate);

            writer.WriteNumber("worker", jobAssignment.Worker);
        }
    }
}
