// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// A simplified view of a [&#x60;Job&#x60;] suitable for JSON responses (dates as strings rather than &#x60;time::Date&#x60;).
    /// </summary>
    public partial class JobDetail : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JobDetail" /> class.
        /// </summary>
        /// <param name="address">address</param>
        /// <param name="date">date</param>
        /// <param name="id">id</param>
        /// <param name="notes">notes</param>
        /// <param name="servicecode">servicecode</param>
        /// <param name="sitename">sitename</param>
        /// <param name="workorder">workorder</param>
        [JsonConstructor]
        public JobDetail(string address, string date, long id, string notes, string servicecode, string sitename, string workorder)
        {
            Address = address;
            Date = date;
            Id = id;
            Notes = notes;
            Servicecode = servicecode;
            Sitename = sitename;
            Workorder = workorder;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [JsonPropertyName("address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [JsonPropertyName("date")]
        public string Date { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public long Id { get; set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        [JsonPropertyName("notes")]
        public string Notes { get; set; }

        /// <summary>
        /// Gets or Sets Servicecode
        /// </summary>
        [JsonPropertyName("servicecode")]
        public string Servicecode { get; set; }

        /// <summary>
        /// Gets or Sets Sitename
        /// </summary>
        [JsonPropertyName("sitename")]
        public string Sitename { get; set; }

        /// <summary>
        /// Gets or Sets Workorder
        /// </summary>
        [JsonPropertyName("workorder")]
        public string Workorder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JobDetail {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  Servicecode: ").Append(Servicecode).Append("\n");
            sb.Append("  Sitename: ").Append(Sitename).Append("\n");
            sb.Append("  Workorder: ").Append(Workorder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="JobDetail" />
    /// </summary>
    public class JobDetailJsonConverter : JsonConverter<JobDetail>
    {
        /// <summary>
        /// Deserializes json to <see cref="JobDetail" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override JobDetail Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> address = default;
            Option<string?> date = default;
            Option<long?> id = default;
            Option<string?> notes = default;
            Option<string?> servicecode = default;
            Option<string?> sitename = default;
            Option<string?> workorder = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "address":
                            address = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "date":
                            date = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "id":
                            id = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "notes":
                            notes = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "servicecode":
                            servicecode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sitename":
                            sitename = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "workorder":
                            workorder = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!address.IsSet)
                throw new ArgumentException("Property is required for class JobDetail.", nameof(address));

            if (!date.IsSet)
                throw new ArgumentException("Property is required for class JobDetail.", nameof(date));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class JobDetail.", nameof(id));

            if (!notes.IsSet)
                throw new ArgumentException("Property is required for class JobDetail.", nameof(notes));

            if (!servicecode.IsSet)
                throw new ArgumentException("Property is required for class JobDetail.", nameof(servicecode));

            if (!sitename.IsSet)
                throw new ArgumentException("Property is required for class JobDetail.", nameof(sitename));

            if (!workorder.IsSet)
                throw new ArgumentException("Property is required for class JobDetail.", nameof(workorder));

            if (address.IsSet && address.Value == null)
                throw new ArgumentNullException(nameof(address), "Property is not nullable for class JobDetail.");

            if (date.IsSet && date.Value == null)
                throw new ArgumentNullException(nameof(date), "Property is not nullable for class JobDetail.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class JobDetail.");

            if (notes.IsSet && notes.Value == null)
                throw new ArgumentNullException(nameof(notes), "Property is not nullable for class JobDetail.");

            if (servicecode.IsSet && servicecode.Value == null)
                throw new ArgumentNullException(nameof(servicecode), "Property is not nullable for class JobDetail.");

            if (sitename.IsSet && sitename.Value == null)
                throw new ArgumentNullException(nameof(sitename), "Property is not nullable for class JobDetail.");

            if (workorder.IsSet && workorder.Value == null)
                throw new ArgumentNullException(nameof(workorder), "Property is not nullable for class JobDetail.");

            return new JobDetail(address.Value!, date.Value!, id.Value!.Value!, notes.Value!, servicecode.Value!, sitename.Value!, workorder.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="JobDetail" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobDetail"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, JobDetail jobDetail, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, jobDetail, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="JobDetail" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobDetail"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, JobDetail jobDetail, JsonSerializerOptions jsonSerializerOptions)
        {
            if (jobDetail.Address == null)
                throw new ArgumentNullException(nameof(jobDetail.Address), "Property is required for class JobDetail.");

            if (jobDetail.Date == null)
                throw new ArgumentNullException(nameof(jobDetail.Date), "Property is required for class JobDetail.");

            if (jobDetail.Notes == null)
                throw new ArgumentNullException(nameof(jobDetail.Notes), "Property is required for class JobDetail.");

            if (jobDetail.Servicecode == null)
                throw new ArgumentNullException(nameof(jobDetail.Servicecode), "Property is required for class JobDetail.");

            if (jobDetail.Sitename == null)
                throw new ArgumentNullException(nameof(jobDetail.Sitename), "Property is required for class JobDetail.");

            if (jobDetail.Workorder == null)
                throw new ArgumentNullException(nameof(jobDetail.Workorder), "Property is required for class JobDetail.");

            writer.WriteString("address", jobDetail.Address);

            writer.WriteString("date", jobDetail.Date);

            writer.WriteNumber("id", jobDetail.Id);

            writer.WriteString("notes", jobDetail.Notes);

            writer.WriteString("servicecode", jobDetail.Servicecode);

            writer.WriteString("sitename", jobDetail.Sitename);

            writer.WriteString("workorder", jobDetail.Workorder);
        }
    }
}
