// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// JobData
    /// </summary>
    public partial class JobData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JobData" /> class.
        /// </summary>
        /// <param name="address">address</param>
        /// <param name="date">date</param>
        /// <param name="jobId">jobId</param>
        /// <param name="jobName">jobName</param>
        /// <param name="notes">notes</param>
        /// <param name="serviceCode">serviceCode</param>
        /// <param name="status">status</param>
        /// <param name="workOrder">workOrder</param>
        /// <param name="workerName">workerName</param>
        /// <param name="workerId">workerId</param>
        [JsonConstructor]
        public JobData(string address, string date, long jobId, string jobName, string notes, string serviceCode, Status status, string workOrder, string workerName, Option<long?> workerId = default)
        {
            Address = address;
            Date = date;
            JobId = jobId;
            JobName = jobName;
            Notes = notes;
            ServiceCode = serviceCode;
            Status = status;
            WorkOrder = workOrder;
            WorkerName = workerName;
            WorkerIdOption = workerId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public Status Status { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [JsonPropertyName("address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [JsonPropertyName("date")]
        public string Date { get; set; }

        /// <summary>
        /// Gets or Sets JobId
        /// </summary>
        [JsonPropertyName("job_id")]
        public long JobId { get; set; }

        /// <summary>
        /// Gets or Sets JobName
        /// </summary>
        [JsonPropertyName("job_name")]
        public string JobName { get; set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        [JsonPropertyName("notes")]
        public string Notes { get; set; }

        /// <summary>
        /// Gets or Sets ServiceCode
        /// </summary>
        [JsonPropertyName("service_code")]
        public string ServiceCode { get; set; }

        /// <summary>
        /// Gets or Sets WorkOrder
        /// </summary>
        [JsonPropertyName("work_order")]
        public string WorkOrder { get; set; }

        /// <summary>
        /// Gets or Sets WorkerName
        /// </summary>
        [JsonPropertyName("worker_name")]
        public string WorkerName { get; set; }

        /// <summary>
        /// Used to track the state of WorkerId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> WorkerIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets WorkerId
        /// </summary>
        [JsonPropertyName("worker_id")]
        public long? WorkerId { get { return this.WorkerIdOption.Value; } set { this.WorkerIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JobData {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  JobId: ").Append(JobId).Append("\n");
            sb.Append("  JobName: ").Append(JobName).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  ServiceCode: ").Append(ServiceCode).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  WorkOrder: ").Append(WorkOrder).Append("\n");
            sb.Append("  WorkerName: ").Append(WorkerName).Append("\n");
            sb.Append("  WorkerId: ").Append(WorkerId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="JobData" />
    /// </summary>
    public class JobDataJsonConverter : JsonConverter<JobData>
    {
        /// <summary>
        /// Deserializes json to <see cref="JobData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override JobData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> address = default;
            Option<string?> date = default;
            Option<long?> jobId = default;
            Option<string?> jobName = default;
            Option<string?> notes = default;
            Option<string?> serviceCode = default;
            Option<Status?> status = default;
            Option<string?> workOrder = default;
            Option<string?> workerName = default;
            Option<long?> workerId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "address":
                            address = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "date":
                            date = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "job_id":
                            jobId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "job_name":
                            jobName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "notes":
                            notes = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "service_code":
                            serviceCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<Status?>(StatusValueConverter.FromStringOrDefault(statusRawValue));
                            break;
                        case "work_order":
                            workOrder = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "worker_name":
                            workerName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "worker_id":
                            workerId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!address.IsSet)
                throw new ArgumentException("Property is required for class JobData.", nameof(address));

            if (!date.IsSet)
                throw new ArgumentException("Property is required for class JobData.", nameof(date));

            if (!jobId.IsSet)
                throw new ArgumentException("Property is required for class JobData.", nameof(jobId));

            if (!jobName.IsSet)
                throw new ArgumentException("Property is required for class JobData.", nameof(jobName));

            if (!notes.IsSet)
                throw new ArgumentException("Property is required for class JobData.", nameof(notes));

            if (!serviceCode.IsSet)
                throw new ArgumentException("Property is required for class JobData.", nameof(serviceCode));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class JobData.", nameof(status));

            if (!workOrder.IsSet)
                throw new ArgumentException("Property is required for class JobData.", nameof(workOrder));

            if (!workerName.IsSet)
                throw new ArgumentException("Property is required for class JobData.", nameof(workerName));

            if (address.IsSet && address.Value == null)
                throw new ArgumentNullException(nameof(address), "Property is not nullable for class JobData.");

            if (date.IsSet && date.Value == null)
                throw new ArgumentNullException(nameof(date), "Property is not nullable for class JobData.");

            if (jobId.IsSet && jobId.Value == null)
                throw new ArgumentNullException(nameof(jobId), "Property is not nullable for class JobData.");

            if (jobName.IsSet && jobName.Value == null)
                throw new ArgumentNullException(nameof(jobName), "Property is not nullable for class JobData.");

            if (notes.IsSet && notes.Value == null)
                throw new ArgumentNullException(nameof(notes), "Property is not nullable for class JobData.");

            if (serviceCode.IsSet && serviceCode.Value == null)
                throw new ArgumentNullException(nameof(serviceCode), "Property is not nullable for class JobData.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class JobData.");

            if (workOrder.IsSet && workOrder.Value == null)
                throw new ArgumentNullException(nameof(workOrder), "Property is not nullable for class JobData.");

            if (workerName.IsSet && workerName.Value == null)
                throw new ArgumentNullException(nameof(workerName), "Property is not nullable for class JobData.");

            return new JobData(address.Value!, date.Value!, jobId.Value!.Value!, jobName.Value!, notes.Value!, serviceCode.Value!, status.Value!.Value!, workOrder.Value!, workerName.Value!, workerId);
        }

        /// <summary>
        /// Serializes a <see cref="JobData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, JobData jobData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, jobData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="JobData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, JobData jobData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (jobData.Address == null)
                throw new ArgumentNullException(nameof(jobData.Address), "Property is required for class JobData.");

            if (jobData.Date == null)
                throw new ArgumentNullException(nameof(jobData.Date), "Property is required for class JobData.");

            if (jobData.JobName == null)
                throw new ArgumentNullException(nameof(jobData.JobName), "Property is required for class JobData.");

            if (jobData.Notes == null)
                throw new ArgumentNullException(nameof(jobData.Notes), "Property is required for class JobData.");

            if (jobData.ServiceCode == null)
                throw new ArgumentNullException(nameof(jobData.ServiceCode), "Property is required for class JobData.");

            if (jobData.WorkOrder == null)
                throw new ArgumentNullException(nameof(jobData.WorkOrder), "Property is required for class JobData.");

            if (jobData.WorkerName == null)
                throw new ArgumentNullException(nameof(jobData.WorkerName), "Property is required for class JobData.");

            writer.WriteString("address", jobData.Address);

            writer.WriteString("date", jobData.Date);

            writer.WriteNumber("job_id", jobData.JobId);

            writer.WriteString("job_name", jobData.JobName);

            writer.WriteString("notes", jobData.Notes);

            writer.WriteString("service_code", jobData.ServiceCode);

            var statusRawValue = StatusValueConverter.ToJsonValue(jobData.Status);
            writer.WriteString("status", statusRawValue);

            writer.WriteString("work_order", jobData.WorkOrder);

            writer.WriteString("worker_name", jobData.WorkerName);

            if (jobData.WorkerIdOption.IsSet)
                if (jobData.WorkerIdOption.Value != null)
                    writer.WriteNumber("worker_id", jobData.WorkerIdOption.Value!.Value);
                else
                    writer.WriteNull("worker_id");
        }
    }
}
