// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Request body shared by the web form and the JSON API for creating or updating a job. &#x60;job_id&#x60; is &#x60;None&#x60; when creating a new job.
    /// </summary>
    public partial class JobEditInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JobEditInput" /> class.
        /// </summary>
        /// <param name="address">address</param>
        /// <param name="assignments">assignments</param>
        /// <param name="date">date</param>
        /// <param name="notes">notes</param>
        /// <param name="servcode">servcode</param>
        /// <param name="sitename">sitename</param>
        /// <param name="workorder">workorder</param>
        /// <param name="jobId">jobId</param>
        [JsonConstructor]
        public JobEditInput(string address, List<JobAssignment> assignments, DateOnly date, string notes, string servcode, string sitename, string workorder, Option<long?> jobId = default)
        {
            Address = address;
            Assignments = assignments;
            Date = date;
            Notes = notes;
            Servcode = servcode;
            Sitename = sitename;
            Workorder = workorder;
            JobIdOption = jobId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [JsonPropertyName("address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or Sets Assignments
        /// </summary>
        [JsonPropertyName("assignments")]
        public List<JobAssignment> Assignments { get; set; }

        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [JsonPropertyName("date")]
        public DateOnly Date { get; set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        [JsonPropertyName("notes")]
        public string Notes { get; set; }

        /// <summary>
        /// Gets or Sets Servcode
        /// </summary>
        [JsonPropertyName("servcode")]
        public string Servcode { get; set; }

        /// <summary>
        /// Gets or Sets Sitename
        /// </summary>
        [JsonPropertyName("sitename")]
        public string Sitename { get; set; }

        /// <summary>
        /// Gets or Sets Workorder
        /// </summary>
        [JsonPropertyName("workorder")]
        public string Workorder { get; set; }

        /// <summary>
        /// Used to track the state of JobId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> JobIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets JobId
        /// </summary>
        [JsonPropertyName("job_id")]
        public long? JobId { get { return this.JobIdOption.Value; } set { this.JobIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JobEditInput {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Assignments: ").Append(Assignments).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  Servcode: ").Append(Servcode).Append("\n");
            sb.Append("  Sitename: ").Append(Sitename).Append("\n");
            sb.Append("  Workorder: ").Append(Workorder).Append("\n");
            sb.Append("  JobId: ").Append(JobId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="JobEditInput" />
    /// </summary>
    public class JobEditInputJsonConverter : JsonConverter<JobEditInput>
    {
        /// <summary>
        /// The format to use to serialize Date
        /// </summary>
        public static string DateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="JobEditInput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override JobEditInput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> address = default;
            Option<List<JobAssignment>?> assignments = default;
            Option<DateOnly?> date = default;
            Option<string?> notes = default;
            Option<string?> servcode = default;
            Option<string?> sitename = default;
            Option<string?> workorder = default;
            Option<long?> jobId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "address":
                            address = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "assignments":
                            assignments = new Option<List<JobAssignment>?>(JsonSerializer.Deserialize<List<JobAssignment>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "date":
                            date = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "notes":
                            notes = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "servcode":
                            servcode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sitename":
                            sitename = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "workorder":
                            workorder = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "job_id":
                            jobId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!address.IsSet)
                throw new ArgumentException("Property is required for class JobEditInput.", nameof(address));

            if (!assignments.IsSet)
                throw new ArgumentException("Property is required for class JobEditInput.", nameof(assignments));

            if (!date.IsSet)
                throw new ArgumentException("Property is required for class JobEditInput.", nameof(date));

            if (!notes.IsSet)
                throw new ArgumentException("Property is required for class JobEditInput.", nameof(notes));

            if (!servcode.IsSet)
                throw new ArgumentException("Property is required for class JobEditInput.", nameof(servcode));

            if (!sitename.IsSet)
                throw new ArgumentException("Property is required for class JobEditInput.", nameof(sitename));

            if (!workorder.IsSet)
                throw new ArgumentException("Property is required for class JobEditInput.", nameof(workorder));

            if (address.IsSet && address.Value == null)
                throw new ArgumentNullException(nameof(address), "Property is not nullable for class JobEditInput.");

            if (assignments.IsSet && assignments.Value == null)
                throw new ArgumentNullException(nameof(assignments), "Property is not nullable for class JobEditInput.");

            if (date.IsSet && date.Value == null)
                throw new ArgumentNullException(nameof(date), "Property is not nullable for class JobEditInput.");

            if (notes.IsSet && notes.Value == null)
                throw new ArgumentNullException(nameof(notes), "Property is not nullable for class JobEditInput.");

            if (servcode.IsSet && servcode.Value == null)
                throw new ArgumentNullException(nameof(servcode), "Property is not nullable for class JobEditInput.");

            if (sitename.IsSet && sitename.Value == null)
                throw new ArgumentNullException(nameof(sitename), "Property is not nullable for class JobEditInput.");

            if (workorder.IsSet && workorder.Value == null)
                throw new ArgumentNullException(nameof(workorder), "Property is not nullable for class JobEditInput.");

            return new JobEditInput(address.Value!, assignments.Value!, date.Value!.Value!, notes.Value!, servcode.Value!, sitename.Value!, workorder.Value!, jobId);
        }

        /// <summary>
        /// Serializes a <see cref="JobEditInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobEditInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, JobEditInput jobEditInput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, jobEditInput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="JobEditInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobEditInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, JobEditInput jobEditInput, JsonSerializerOptions jsonSerializerOptions)
        {
            if (jobEditInput.Address == null)
                throw new ArgumentNullException(nameof(jobEditInput.Address), "Property is required for class JobEditInput.");

            if (jobEditInput.Assignments == null)
                throw new ArgumentNullException(nameof(jobEditInput.Assignments), "Property is required for class JobEditInput.");

            if (jobEditInput.Notes == null)
                throw new ArgumentNullException(nameof(jobEditInput.Notes), "Property is required for class JobEditInput.");

            if (jobEditInput.Servcode == null)
                throw new ArgumentNullException(nameof(jobEditInput.Servcode), "Property is required for class JobEditInput.");

            if (jobEditInput.Sitename == null)
                throw new ArgumentNullException(nameof(jobEditInput.Sitename), "Property is required for class JobEditInput.");

            if (jobEditInput.Workorder == null)
                throw new ArgumentNullException(nameof(jobEditInput.Workorder), "Property is required for class JobEditInput.");

            writer.WriteString("address", jobEditInput.Address);

            writer.WritePropertyName("assignments");
            JsonSerializer.Serialize(writer, jobEditInput.Assignments, jsonSerializerOptions);
            writer.WriteString("date", jobEditInput.Date.ToString(DateFormat));

            writer.WriteString("notes", jobEditInput.Notes);

            writer.WriteString("servcode", jobEditInput.Servcode);

            writer.WriteString("sitename", jobEditInput.Sitename);

            writer.WriteString("workorder", jobEditInput.Workorder);

            if (jobEditInput.JobIdOption.IsSet)
                if (jobEditInput.JobIdOption.Value != null)
                    writer.WriteNumber("job_id", jobEditInput.JobIdOption.Value!.Value);
                else
                    writer.WriteNull("job_id");
        }
    }
}
