// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// The data needed to render (or serve as JSON) the job-edit page: the job itself (&#x60;None&#x60; when creating a new job) and every active worker along with their assignment status on it.
    /// </summary>
    public partial class JobEditPageOutput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JobEditPageOutput" /> class.
        /// </summary>
        /// <param name="workers">workers</param>
        /// <param name="job">job</param>
        [JsonConstructor]
        public JobEditPageOutput(List<WorkerAssignmentInfo> workers, Option<JobDetail?> job = default)
        {
            Workers = workers;
            JobOption = job;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Workers
        /// </summary>
        [JsonPropertyName("workers")]
        public List<WorkerAssignmentInfo> Workers { get; set; }

        /// <summary>
        /// Used to track the state of Job
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<JobDetail?> JobOption { get; private set; }

        /// <summary>
        /// Gets or Sets Job
        /// </summary>
        [JsonPropertyName("job")]
        public JobDetail? Job { get { return this.JobOption.Value; } set { this.JobOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JobEditPageOutput {\n");
            sb.Append("  Workers: ").Append(Workers).Append("\n");
            sb.Append("  Job: ").Append(Job).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="JobEditPageOutput" />
    /// </summary>
    public class JobEditPageOutputJsonConverter : JsonConverter<JobEditPageOutput>
    {
        /// <summary>
        /// Deserializes json to <see cref="JobEditPageOutput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override JobEditPageOutput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<WorkerAssignmentInfo>?> workers = default;
            Option<JobDetail?> job = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "workers":
                            workers = new Option<List<WorkerAssignmentInfo>?>(JsonSerializer.Deserialize<List<WorkerAssignmentInfo>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "job":
                            job = new Option<JobDetail?>(JsonSerializer.Deserialize<JobDetail>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!workers.IsSet)
                throw new ArgumentException("Property is required for class JobEditPageOutput.", nameof(workers));

            if (workers.IsSet && workers.Value == null)
                throw new ArgumentNullException(nameof(workers), "Property is not nullable for class JobEditPageOutput.");

            return new JobEditPageOutput(workers.Value!, job);
        }

        /// <summary>
        /// Serializes a <see cref="JobEditPageOutput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobEditPageOutput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, JobEditPageOutput jobEditPageOutput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, jobEditPageOutput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="JobEditPageOutput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobEditPageOutput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, JobEditPageOutput jobEditPageOutput, JsonSerializerOptions jsonSerializerOptions)
        {
            if (jobEditPageOutput.Workers == null)
                throw new ArgumentNullException(nameof(jobEditPageOutput.Workers), "Property is required for class JobEditPageOutput.");

            writer.WritePropertyName("workers");
            JsonSerializer.Serialize(writer, jobEditPageOutput.Workers, jsonSerializerOptions);
            if (jobEditPageOutput.JobOption.IsSet)
                if (jobEditPageOutput.JobOption.Value != null)
                {
                    writer.WritePropertyName("job");
                    JsonSerializer.Serialize(writer, jobEditPageOutput.Job, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("job");
        }
    }
}
