// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// The full result of a job-list search: every matching job/assignment row plus the (possibly defaulted) search parameters that produced it. Shared by both the HTML page and the JSON API.
    /// </summary>
    public partial class JobListOutput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JobListOutput" /> class.
        /// </summary>
        /// <param name="admin">admin</param>
        /// <param name="assigned">assigned</param>
        /// <param name="completed">completed</param>
        /// <param name="count">count</param>
        /// <param name="jobs">jobs</param>
        /// <param name="order">order</param>
        /// <param name="params">params</param>
        /// <param name="started">started</param>
        [JsonConstructor]
        public JobListOutput(bool admin, bool assigned, bool completed, int count, List<JobData> jobs, Order order, SearchParams @params, bool started)
        {
            Admin = admin;
            Assigned = assigned;
            Completed = completed;
            Count = count;
            Jobs = jobs;
            Order = order;
            Params = @params;
            Started = started;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Order
        /// </summary>
        [JsonPropertyName("order")]
        public Order Order { get; set; }

        /// <summary>
        /// Gets or Sets Admin
        /// </summary>
        [JsonPropertyName("admin")]
        public bool Admin { get; set; }

        /// <summary>
        /// Gets or Sets Assigned
        /// </summary>
        [JsonPropertyName("assigned")]
        public bool Assigned { get; set; }

        /// <summary>
        /// Gets or Sets Completed
        /// </summary>
        [JsonPropertyName("completed")]
        public bool Completed { get; set; }

        /// <summary>
        /// Gets or Sets Count
        /// </summary>
        [JsonPropertyName("count")]
        public int Count { get; set; }

        /// <summary>
        /// Gets or Sets Jobs
        /// </summary>
        [JsonPropertyName("jobs")]
        public List<JobData> Jobs { get; set; }

        /// <summary>
        /// Gets or Sets Params
        /// </summary>
        [JsonPropertyName("params")]
        public SearchParams Params { get; set; }

        /// <summary>
        /// Gets or Sets Started
        /// </summary>
        [JsonPropertyName("started")]
        public bool Started { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JobListOutput {\n");
            sb.Append("  Admin: ").Append(Admin).Append("\n");
            sb.Append("  Assigned: ").Append(Assigned).Append("\n");
            sb.Append("  Completed: ").Append(Completed).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  Jobs: ").Append(Jobs).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("  Params: ").Append(Params).Append("\n");
            sb.Append("  Started: ").Append(Started).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Count (int) minimum
            if (this.Count < (int)0)
            {
                yield return new ValidationResult("Invalid value for Count, must be a value greater than or equal to 0.", new [] { "Count" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="JobListOutput" />
    /// </summary>
    public class JobListOutputJsonConverter : JsonConverter<JobListOutput>
    {
        /// <summary>
        /// Deserializes json to <see cref="JobListOutput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override JobListOutput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> admin = default;
            Option<bool?> assigned = default;
            Option<bool?> completed = default;
            Option<int?> count = default;
            Option<List<JobData>?> jobs = default;
            Option<Order?> order = default;
            Option<SearchParams?> varParams = default;
            Option<bool?> started = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "admin":
                            admin = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "assigned":
                            assigned = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "completed":
                            completed = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "count":
                            count = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "jobs":
                            jobs = new Option<List<JobData>?>(JsonSerializer.Deserialize<List<JobData>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "order":
                            string? orderRawValue = utf8JsonReader.GetString();
                            if (orderRawValue != null)
                                order = new Option<Order?>(OrderValueConverter.FromStringOrDefault(orderRawValue));
                            break;
                        case "params":
                            varParams = new Option<SearchParams?>(JsonSerializer.Deserialize<SearchParams>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "started":
                            started = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!admin.IsSet)
                throw new ArgumentException("Property is required for class JobListOutput.", nameof(admin));

            if (!assigned.IsSet)
                throw new ArgumentException("Property is required for class JobListOutput.", nameof(assigned));

            if (!completed.IsSet)
                throw new ArgumentException("Property is required for class JobListOutput.", nameof(completed));

            if (!count.IsSet)
                throw new ArgumentException("Property is required for class JobListOutput.", nameof(count));

            if (!jobs.IsSet)
                throw new ArgumentException("Property is required for class JobListOutput.", nameof(jobs));

            if (!order.IsSet)
                throw new ArgumentException("Property is required for class JobListOutput.", nameof(order));

            if (!varParams.IsSet)
                throw new ArgumentException("Property is required for class JobListOutput.", nameof(varParams));

            if (!started.IsSet)
                throw new ArgumentException("Property is required for class JobListOutput.", nameof(started));

            if (admin.IsSet && admin.Value == null)
                throw new ArgumentNullException(nameof(admin), "Property is not nullable for class JobListOutput.");

            if (assigned.IsSet && assigned.Value == null)
                throw new ArgumentNullException(nameof(assigned), "Property is not nullable for class JobListOutput.");

            if (completed.IsSet && completed.Value == null)
                throw new ArgumentNullException(nameof(completed), "Property is not nullable for class JobListOutput.");

            if (count.IsSet && count.Value == null)
                throw new ArgumentNullException(nameof(count), "Property is not nullable for class JobListOutput.");

            if (jobs.IsSet && jobs.Value == null)
                throw new ArgumentNullException(nameof(jobs), "Property is not nullable for class JobListOutput.");

            if (order.IsSet && order.Value == null)
                throw new ArgumentNullException(nameof(order), "Property is not nullable for class JobListOutput.");

            if (varParams.IsSet && varParams.Value == null)
                throw new ArgumentNullException(nameof(varParams), "Property is not nullable for class JobListOutput.");

            if (started.IsSet && started.Value == null)
                throw new ArgumentNullException(nameof(started), "Property is not nullable for class JobListOutput.");

            return new JobListOutput(admin.Value!.Value!, assigned.Value!.Value!, completed.Value!.Value!, count.Value!.Value!, jobs.Value!, order.Value!.Value!, varParams.Value!, started.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="JobListOutput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobListOutput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, JobListOutput jobListOutput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, jobListOutput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="JobListOutput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobListOutput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, JobListOutput jobListOutput, JsonSerializerOptions jsonSerializerOptions)
        {
            if (jobListOutput.Jobs == null)
                throw new ArgumentNullException(nameof(jobListOutput.Jobs), "Property is required for class JobListOutput.");

            if (jobListOutput.Params == null)
                throw new ArgumentNullException(nameof(jobListOutput.Params), "Property is required for class JobListOutput.");

            writer.WriteBoolean("admin", jobListOutput.Admin);

            writer.WriteBoolean("assigned", jobListOutput.Assigned);

            writer.WriteBoolean("completed", jobListOutput.Completed);

            writer.WriteNumber("count", jobListOutput.Count);

            writer.WritePropertyName("jobs");
            JsonSerializer.Serialize(writer, jobListOutput.Jobs, jsonSerializerOptions);
            var orderRawValue = OrderValueConverter.ToJsonValue(jobListOutput.Order);
            writer.WriteString("order", orderRawValue);

            writer.WritePropertyName("params");
            JsonSerializer.Serialize(writer, jobListOutput.Params, jsonSerializerOptions);
            writer.WriteBoolean("started", jobListOutput.Started);
        }
    }
}
