// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// The outcome of attempting to log in. &#x60;must_change_pw&#x60; is &#x60;true&#x60; when the credentials were valid but the account is required to change its password before a session (or, for the API, a token) can be issued. On the web this always redirects rather than returning this body; the API returns it directly.  &#x60;token&#x60; is only ever populated by the JSON API (&#x60;POST /api/v1/login&#x60;): it&#39;s the bearer token to send as &#x60;Authorization: Bearer &lt;token&gt;&#x60; on every subsequent &#x60;/api/v1/_*&#x60; or &#x60;/admin/api/v1/_*&#x60; request. The HTML UI doesn&#39;t use tokens at all - it authenticates via a cookie session instead, so &#x60;token&#x60; is always &#x60;None&#x60; there.
    /// </summary>
    public partial class LoginOutput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LoginOutput" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="mustChangePw">mustChangePw</param>
        /// <param name="username">username</param>
        /// <param name="token">token</param>
        [JsonConstructor]
        public LoginOutput(long id, bool mustChangePw, string username, Option<string?> token = default)
        {
            Id = id;
            MustChangePw = mustChangePw;
            Username = username;
            TokenOption = token;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public long Id { get; set; }

        /// <summary>
        /// Gets or Sets MustChangePw
        /// </summary>
        [JsonPropertyName("must_change_pw")]
        public bool MustChangePw { get; set; }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        [JsonPropertyName("username")]
        public string Username { get; set; }

        /// <summary>
        /// Used to track the state of Token
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TokenOption { get; private set; }

        /// <summary>
        /// Gets or Sets Token
        /// </summary>
        [JsonPropertyName("token")]
        public string? Token { get { return this.TokenOption.Value; } set { this.TokenOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LoginOutput {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  MustChangePw: ").Append(MustChangePw).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LoginOutput" />
    /// </summary>
    public class LoginOutputJsonConverter : JsonConverter<LoginOutput>
    {
        /// <summary>
        /// Deserializes json to <see cref="LoginOutput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LoginOutput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> id = default;
            Option<bool?> mustChangePw = default;
            Option<string?> username = default;
            Option<string?> token = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "must_change_pw":
                            mustChangePw = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "username":
                            username = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "token":
                            token = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class LoginOutput.", nameof(id));

            if (!mustChangePw.IsSet)
                throw new ArgumentException("Property is required for class LoginOutput.", nameof(mustChangePw));

            if (!username.IsSet)
                throw new ArgumentException("Property is required for class LoginOutput.", nameof(username));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class LoginOutput.");

            if (mustChangePw.IsSet && mustChangePw.Value == null)
                throw new ArgumentNullException(nameof(mustChangePw), "Property is not nullable for class LoginOutput.");

            if (username.IsSet && username.Value == null)
                throw new ArgumentNullException(nameof(username), "Property is not nullable for class LoginOutput.");

            return new LoginOutput(id.Value!.Value!, mustChangePw.Value!.Value!, username.Value!, token);
        }

        /// <summary>
        /// Serializes a <see cref="LoginOutput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="loginOutput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, LoginOutput loginOutput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, loginOutput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="LoginOutput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="loginOutput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, LoginOutput loginOutput, JsonSerializerOptions jsonSerializerOptions)
        {
            if (loginOutput.Username == null)
                throw new ArgumentNullException(nameof(loginOutput.Username), "Property is required for class LoginOutput.");

            writer.WriteNumber("id", loginOutput.Id);

            writer.WriteBoolean("must_change_pw", loginOutput.MustChangePw);

            writer.WriteString("username", loginOutput.Username);

            if (loginOutput.TokenOption.IsSet)
                if (loginOutput.TokenOption.Value != null)
                    writer.WriteString("token", loginOutput.Token);
                else
                    writer.WriteNull("token");
        }
    }
}
