// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// LogoutOutput
    /// </summary>
    public partial class LogoutOutput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LogoutOutput" /> class.
        /// </summary>
        /// <param name="loggedOut">loggedOut</param>
        [JsonConstructor]
        public LogoutOutput(bool loggedOut)
        {
            LoggedOut = loggedOut;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets LoggedOut
        /// </summary>
        [JsonPropertyName("logged_out")]
        public bool LoggedOut { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LogoutOutput {\n");
            sb.Append("  LoggedOut: ").Append(LoggedOut).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LogoutOutput" />
    /// </summary>
    public class LogoutOutputJsonConverter : JsonConverter<LogoutOutput>
    {
        /// <summary>
        /// Deserializes json to <see cref="LogoutOutput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LogoutOutput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> loggedOut = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "logged_out":
                            loggedOut = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!loggedOut.IsSet)
                throw new ArgumentException("Property is required for class LogoutOutput.", nameof(loggedOut));

            if (loggedOut.IsSet && loggedOut.Value == null)
                throw new ArgumentNullException(nameof(loggedOut), "Property is not nullable for class LogoutOutput.");

            return new LogoutOutput(loggedOut.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="LogoutOutput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="logoutOutput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, LogoutOutput logoutOutput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, logoutOutput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="LogoutOutput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="logoutOutput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, LogoutOutput logoutOutput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteBoolean("logged_out", logoutOutput.LoggedOut);
        }
    }
}
