// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines Order
    /// </summary>
    public enum Order
    {
        /// <summary>
        /// Enum Latest for value: Latest
        /// </summary>
        Latest = 1,

        /// <summary>
        /// Enum Earliest for value: Earliest
        /// </summary>
        Earliest = 2
    }

    /// <summary>
    /// Converts <see cref="Order"/> to and from the JSON value
    /// </summary>
    public static class OrderValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="Order"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static Order FromString(string value)
        {
            if (value.Equals("Latest"))
                return Order.Latest;

            if (value.Equals("Earliest"))
                return Order.Earliest;

            throw new NotImplementedException($"Could not convert value to type Order: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="Order"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static Order? FromStringOrDefault(string value)
        {
            if (value.Equals("Latest"))
                return Order.Latest;

            if (value.Equals("Earliest"))
                return Order.Earliest;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="Order"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(Order value)
        {
            if (value == Order.Latest)
                return "Latest";

            if (value == Order.Earliest)
                return "Earliest";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Order"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class OrderJsonConverter : JsonConverter<Order>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override Order Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            Order? result = rawValue == null
                ? null
                : OrderValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the Order to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="order"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, Order order, JsonSerializerOptions options)
        {
            writer.WriteStringValue(OrderValueConverter.ToJsonValue(order).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Order"/>
    /// </summary>
    public class OrderNullableJsonConverter : JsonConverter<Order?>
    {
        /// <summary>
        /// Returns a Order from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override Order? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            Order? result = rawValue == null
                ? null
                : OrderValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the Order to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="order"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, Order? order, JsonSerializerOptions options)
        {
            writer.WriteStringValue(order.HasValue ? OrderValueConverter.ToJsonValue(order.Value).ToString() : "null");
        }
    }
}
