// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SearchParams
    /// </summary>
    public partial class SearchParams : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchParams" /> class.
        /// </summary>
        /// <param name="address">address</param>
        /// <param name="end">end</param>
        /// <param name="fieldnotes">fieldnotes</param>
        /// <param name="siteName">siteName</param>
        /// <param name="start">start</param>
        /// <param name="workOrder">workOrder</param>
        /// <param name="workers">workers</param>
        [JsonConstructor]
        public SearchParams(string address, string end, string fieldnotes, string siteName, string start, string workOrder, List<WorkerFilterOption> workers)
        {
            Address = address;
            End = end;
            Fieldnotes = fieldnotes;
            SiteName = siteName;
            Start = start;
            WorkOrder = workOrder;
            Workers = workers;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [JsonPropertyName("address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or Sets End
        /// </summary>
        [JsonPropertyName("end")]
        public string End { get; set; }

        /// <summary>
        /// Gets or Sets Fieldnotes
        /// </summary>
        [JsonPropertyName("fieldnotes")]
        public string Fieldnotes { get; set; }

        /// <summary>
        /// Gets or Sets SiteName
        /// </summary>
        [JsonPropertyName("site_name")]
        public string SiteName { get; set; }

        /// <summary>
        /// Gets or Sets Start
        /// </summary>
        [JsonPropertyName("start")]
        public string Start { get; set; }

        /// <summary>
        /// Gets or Sets WorkOrder
        /// </summary>
        [JsonPropertyName("work_order")]
        public string WorkOrder { get; set; }

        /// <summary>
        /// Gets or Sets Workers
        /// </summary>
        [JsonPropertyName("workers")]
        public List<WorkerFilterOption> Workers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchParams {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  End: ").Append(End).Append("\n");
            sb.Append("  Fieldnotes: ").Append(Fieldnotes).Append("\n");
            sb.Append("  SiteName: ").Append(SiteName).Append("\n");
            sb.Append("  Start: ").Append(Start).Append("\n");
            sb.Append("  WorkOrder: ").Append(WorkOrder).Append("\n");
            sb.Append("  Workers: ").Append(Workers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchParams" />
    /// </summary>
    public class SearchParamsJsonConverter : JsonConverter<SearchParams>
    {
        /// <summary>
        /// Deserializes json to <see cref="SearchParams" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SearchParams Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> address = default;
            Option<string?> end = default;
            Option<string?> fieldnotes = default;
            Option<string?> siteName = default;
            Option<string?> start = default;
            Option<string?> workOrder = default;
            Option<List<WorkerFilterOption>?> workers = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "address":
                            address = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "end":
                            end = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "fieldnotes":
                            fieldnotes = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "site_name":
                            siteName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "start":
                            start = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "work_order":
                            workOrder = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "workers":
                            workers = new Option<List<WorkerFilterOption>?>(JsonSerializer.Deserialize<List<WorkerFilterOption>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!address.IsSet)
                throw new ArgumentException("Property is required for class SearchParams.", nameof(address));

            if (!end.IsSet)
                throw new ArgumentException("Property is required for class SearchParams.", nameof(end));

            if (!fieldnotes.IsSet)
                throw new ArgumentException("Property is required for class SearchParams.", nameof(fieldnotes));

            if (!siteName.IsSet)
                throw new ArgumentException("Property is required for class SearchParams.", nameof(siteName));

            if (!start.IsSet)
                throw new ArgumentException("Property is required for class SearchParams.", nameof(start));

            if (!workOrder.IsSet)
                throw new ArgumentException("Property is required for class SearchParams.", nameof(workOrder));

            if (!workers.IsSet)
                throw new ArgumentException("Property is required for class SearchParams.", nameof(workers));

            if (address.IsSet && address.Value == null)
                throw new ArgumentNullException(nameof(address), "Property is not nullable for class SearchParams.");

            if (end.IsSet && end.Value == null)
                throw new ArgumentNullException(nameof(end), "Property is not nullable for class SearchParams.");

            if (fieldnotes.IsSet && fieldnotes.Value == null)
                throw new ArgumentNullException(nameof(fieldnotes), "Property is not nullable for class SearchParams.");

            if (siteName.IsSet && siteName.Value == null)
                throw new ArgumentNullException(nameof(siteName), "Property is not nullable for class SearchParams.");

            if (start.IsSet && start.Value == null)
                throw new ArgumentNullException(nameof(start), "Property is not nullable for class SearchParams.");

            if (workOrder.IsSet && workOrder.Value == null)
                throw new ArgumentNullException(nameof(workOrder), "Property is not nullable for class SearchParams.");

            if (workers.IsSet && workers.Value == null)
                throw new ArgumentNullException(nameof(workers), "Property is not nullable for class SearchParams.");

            return new SearchParams(address.Value!, end.Value!, fieldnotes.Value!, siteName.Value!, start.Value!, workOrder.Value!, workers.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SearchParams" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchParams"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SearchParams searchParams, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, searchParams, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SearchParams" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchParams"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SearchParams searchParams, JsonSerializerOptions jsonSerializerOptions)
        {
            if (searchParams.Address == null)
                throw new ArgumentNullException(nameof(searchParams.Address), "Property is required for class SearchParams.");

            if (searchParams.End == null)
                throw new ArgumentNullException(nameof(searchParams.End), "Property is required for class SearchParams.");

            if (searchParams.Fieldnotes == null)
                throw new ArgumentNullException(nameof(searchParams.Fieldnotes), "Property is required for class SearchParams.");

            if (searchParams.SiteName == null)
                throw new ArgumentNullException(nameof(searchParams.SiteName), "Property is required for class SearchParams.");

            if (searchParams.Start == null)
                throw new ArgumentNullException(nameof(searchParams.Start), "Property is required for class SearchParams.");

            if (searchParams.WorkOrder == null)
                throw new ArgumentNullException(nameof(searchParams.WorkOrder), "Property is required for class SearchParams.");

            if (searchParams.Workers == null)
                throw new ArgumentNullException(nameof(searchParams.Workers), "Property is required for class SearchParams.");

            writer.WriteString("address", searchParams.Address);

            writer.WriteString("end", searchParams.End);

            writer.WriteString("fieldnotes", searchParams.Fieldnotes);

            writer.WriteString("site_name", searchParams.SiteName);

            writer.WriteString("start", searchParams.Start);

            writer.WriteString("work_order", searchParams.WorkOrder);

            writer.WritePropertyName("workers");
            JsonSerializer.Serialize(writer, searchParams.Workers, jsonSerializerOptions);
        }
    }
}
