// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines Status
    /// </summary>
    public enum Status
    {
        /// <summary>
        /// Enum Assigned for value: assigned
        /// </summary>
        Assigned = 1,

        /// <summary>
        /// Enum Started for value: started
        /// </summary>
        Started = 2,

        /// <summary>
        /// Enum Signedout for value: signedout
        /// </summary>
        Signedout = 3,

        /// <summary>
        /// Enum Outnotin for value: outnotin
        /// </summary>
        Outnotin = 4
    }

    /// <summary>
    /// Converts <see cref="Status"/> to and from the JSON value
    /// </summary>
    public static class StatusValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="Status"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static Status FromString(string value)
        {
            if (value.Equals("assigned"))
                return Status.Assigned;

            if (value.Equals("started"))
                return Status.Started;

            if (value.Equals("signedout"))
                return Status.Signedout;

            if (value.Equals("outnotin"))
                return Status.Outnotin;

            throw new NotImplementedException($"Could not convert value to type Status: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="Status"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static Status? FromStringOrDefault(string value)
        {
            if (value.Equals("assigned"))
                return Status.Assigned;

            if (value.Equals("started"))
                return Status.Started;

            if (value.Equals("signedout"))
                return Status.Signedout;

            if (value.Equals("outnotin"))
                return Status.Outnotin;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="Status"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(Status value)
        {
            if (value == Status.Assigned)
                return "assigned";

            if (value == Status.Started)
                return "started";

            if (value == Status.Signedout)
                return "signedout";

            if (value == Status.Outnotin)
                return "outnotin";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Status"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class StatusJsonConverter : JsonConverter<Status>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override Status Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            Status? result = rawValue == null
                ? null
                : StatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the Status to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="status"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, Status status, JsonSerializerOptions options)
        {
            writer.WriteStringValue(StatusValueConverter.ToJsonValue(status).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Status"/>
    /// </summary>
    public class StatusNullableJsonConverter : JsonConverter<Status?>
    {
        /// <summary>
        /// Returns a Status from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override Status? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            Status? result = rawValue == null
                ? null
                : StatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the Status to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="status"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, Status? status, JsonSerializerOptions options)
        {
            writer.WriteStringValue(status.HasValue ? StatusValueConverter.ToJsonValue(status.Value).ToString() : "null");
        }
    }
}
