// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// WDEntry
    /// </summary>
    public partial class WDEntry : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WDEntry" /> class.
        /// </summary>
        /// <param name="completed">completed</param>
        /// <param name="date">date</param>
        /// <param name="extraExpensesDollars">extraExpensesDollars</param>
        /// <param name="flatRate">flatRate</param>
        /// <param name="hoursDriven">hoursDriven</param>
        /// <param name="hoursWorked">hoursWorked</param>
        /// <param name="jobId">jobId</param>
        /// <param name="location">location</param>
        /// <param name="milesDriven">milesDriven</param>
        /// <param name="trueHoursWorked">trueHoursWorked</param>
        /// <param name="workerId">workerId</param>
        [JsonConstructor]
        public WDEntry(bool completed, string date, string extraExpensesDollars, bool flatRate, string hoursDriven, string hoursWorked, long jobId, string location, string milesDriven, string trueHoursWorked, long workerId)
        {
            Completed = completed;
            Date = date;
            ExtraExpensesDollars = extraExpensesDollars;
            FlatRate = flatRate;
            HoursDriven = hoursDriven;
            HoursWorked = hoursWorked;
            JobId = jobId;
            Location = location;
            MilesDriven = milesDriven;
            TrueHoursWorked = trueHoursWorked;
            WorkerId = workerId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Completed
        /// </summary>
        [JsonPropertyName("Completed")]
        public bool Completed { get; set; }

        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [JsonPropertyName("Date")]
        public string Date { get; set; }

        /// <summary>
        /// Gets or Sets ExtraExpensesDollars
        /// </summary>
        [JsonPropertyName("ExtraExpensesDollars")]
        public string ExtraExpensesDollars { get; set; }

        /// <summary>
        /// Gets or Sets FlatRate
        /// </summary>
        [JsonPropertyName("FlatRate")]
        public bool FlatRate { get; set; }

        /// <summary>
        /// Gets or Sets HoursDriven
        /// </summary>
        [JsonPropertyName("HoursDriven")]
        public string HoursDriven { get; set; }

        /// <summary>
        /// Gets or Sets HoursWorked
        /// </summary>
        [JsonPropertyName("HoursWorked")]
        public string HoursWorked { get; set; }

        /// <summary>
        /// Gets or Sets JobId
        /// </summary>
        [JsonPropertyName("JobId")]
        public long JobId { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [JsonPropertyName("Location")]
        public string Location { get; set; }

        /// <summary>
        /// Gets or Sets MilesDriven
        /// </summary>
        [JsonPropertyName("MilesDriven")]
        public string MilesDriven { get; set; }

        /// <summary>
        /// Gets or Sets TrueHoursWorked
        /// </summary>
        [JsonPropertyName("TrueHoursWorked")]
        public string TrueHoursWorked { get; set; }

        /// <summary>
        /// Gets or Sets WorkerId
        /// </summary>
        [JsonPropertyName("WorkerId")]
        public long WorkerId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WDEntry {\n");
            sb.Append("  Completed: ").Append(Completed).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  ExtraExpensesDollars: ").Append(ExtraExpensesDollars).Append("\n");
            sb.Append("  FlatRate: ").Append(FlatRate).Append("\n");
            sb.Append("  HoursDriven: ").Append(HoursDriven).Append("\n");
            sb.Append("  HoursWorked: ").Append(HoursWorked).Append("\n");
            sb.Append("  JobId: ").Append(JobId).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  MilesDriven: ").Append(MilesDriven).Append("\n");
            sb.Append("  TrueHoursWorked: ").Append(TrueHoursWorked).Append("\n");
            sb.Append("  WorkerId: ").Append(WorkerId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WDEntry" />
    /// </summary>
    public class WDEntryJsonConverter : JsonConverter<WDEntry>
    {
        /// <summary>
        /// Deserializes json to <see cref="WDEntry" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WDEntry Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> completed = default;
            Option<string?> date = default;
            Option<string?> extraExpensesDollars = default;
            Option<bool?> flatRate = default;
            Option<string?> hoursDriven = default;
            Option<string?> hoursWorked = default;
            Option<long?> jobId = default;
            Option<string?> location = default;
            Option<string?> milesDriven = default;
            Option<string?> trueHoursWorked = default;
            Option<long?> workerId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "Completed":
                            completed = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "Date":
                            date = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "ExtraExpensesDollars":
                            extraExpensesDollars = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "FlatRate":
                            flatRate = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "HoursDriven":
                            hoursDriven = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "HoursWorked":
                            hoursWorked = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "JobId":
                            jobId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "Location":
                            location = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "MilesDriven":
                            milesDriven = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "TrueHoursWorked":
                            trueHoursWorked = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "WorkerId":
                            workerId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!completed.IsSet)
                throw new ArgumentException("Property is required for class WDEntry.", nameof(completed));

            if (!date.IsSet)
                throw new ArgumentException("Property is required for class WDEntry.", nameof(date));

            if (!extraExpensesDollars.IsSet)
                throw new ArgumentException("Property is required for class WDEntry.", nameof(extraExpensesDollars));

            if (!flatRate.IsSet)
                throw new ArgumentException("Property is required for class WDEntry.", nameof(flatRate));

            if (!hoursDriven.IsSet)
                throw new ArgumentException("Property is required for class WDEntry.", nameof(hoursDriven));

            if (!hoursWorked.IsSet)
                throw new ArgumentException("Property is required for class WDEntry.", nameof(hoursWorked));

            if (!jobId.IsSet)
                throw new ArgumentException("Property is required for class WDEntry.", nameof(jobId));

            if (!location.IsSet)
                throw new ArgumentException("Property is required for class WDEntry.", nameof(location));

            if (!milesDriven.IsSet)
                throw new ArgumentException("Property is required for class WDEntry.", nameof(milesDriven));

            if (!trueHoursWorked.IsSet)
                throw new ArgumentException("Property is required for class WDEntry.", nameof(trueHoursWorked));

            if (!workerId.IsSet)
                throw new ArgumentException("Property is required for class WDEntry.", nameof(workerId));

            if (completed.IsSet && completed.Value == null)
                throw new ArgumentNullException(nameof(completed), "Property is not nullable for class WDEntry.");

            if (date.IsSet && date.Value == null)
                throw new ArgumentNullException(nameof(date), "Property is not nullable for class WDEntry.");

            if (extraExpensesDollars.IsSet && extraExpensesDollars.Value == null)
                throw new ArgumentNullException(nameof(extraExpensesDollars), "Property is not nullable for class WDEntry.");

            if (flatRate.IsSet && flatRate.Value == null)
                throw new ArgumentNullException(nameof(flatRate), "Property is not nullable for class WDEntry.");

            if (hoursDriven.IsSet && hoursDriven.Value == null)
                throw new ArgumentNullException(nameof(hoursDriven), "Property is not nullable for class WDEntry.");

            if (hoursWorked.IsSet && hoursWorked.Value == null)
                throw new ArgumentNullException(nameof(hoursWorked), "Property is not nullable for class WDEntry.");

            if (jobId.IsSet && jobId.Value == null)
                throw new ArgumentNullException(nameof(jobId), "Property is not nullable for class WDEntry.");

            if (location.IsSet && location.Value == null)
                throw new ArgumentNullException(nameof(location), "Property is not nullable for class WDEntry.");

            if (milesDriven.IsSet && milesDriven.Value == null)
                throw new ArgumentNullException(nameof(milesDriven), "Property is not nullable for class WDEntry.");

            if (trueHoursWorked.IsSet && trueHoursWorked.Value == null)
                throw new ArgumentNullException(nameof(trueHoursWorked), "Property is not nullable for class WDEntry.");

            if (workerId.IsSet && workerId.Value == null)
                throw new ArgumentNullException(nameof(workerId), "Property is not nullable for class WDEntry.");

            return new WDEntry(completed.Value!.Value!, date.Value!, extraExpensesDollars.Value!, flatRate.Value!.Value!, hoursDriven.Value!, hoursWorked.Value!, jobId.Value!.Value!, location.Value!, milesDriven.Value!, trueHoursWorked.Value!, workerId.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="WDEntry" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="wDEntry"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WDEntry wDEntry, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, wDEntry, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WDEntry" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="wDEntry"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WDEntry wDEntry, JsonSerializerOptions jsonSerializerOptions)
        {
            if (wDEntry.Date == null)
                throw new ArgumentNullException(nameof(wDEntry.Date), "Property is required for class WDEntry.");

            if (wDEntry.ExtraExpensesDollars == null)
                throw new ArgumentNullException(nameof(wDEntry.ExtraExpensesDollars), "Property is required for class WDEntry.");

            if (wDEntry.HoursDriven == null)
                throw new ArgumentNullException(nameof(wDEntry.HoursDriven), "Property is required for class WDEntry.");

            if (wDEntry.HoursWorked == null)
                throw new ArgumentNullException(nameof(wDEntry.HoursWorked), "Property is required for class WDEntry.");

            if (wDEntry.Location == null)
                throw new ArgumentNullException(nameof(wDEntry.Location), "Property is required for class WDEntry.");

            if (wDEntry.MilesDriven == null)
                throw new ArgumentNullException(nameof(wDEntry.MilesDriven), "Property is required for class WDEntry.");

            if (wDEntry.TrueHoursWorked == null)
                throw new ArgumentNullException(nameof(wDEntry.TrueHoursWorked), "Property is required for class WDEntry.");

            writer.WriteBoolean("Completed", wDEntry.Completed);

            writer.WriteString("Date", wDEntry.Date);

            writer.WriteString("ExtraExpensesDollars", wDEntry.ExtraExpensesDollars);

            writer.WriteBoolean("FlatRate", wDEntry.FlatRate);

            writer.WriteString("HoursDriven", wDEntry.HoursDriven);

            writer.WriteString("HoursWorked", wDEntry.HoursWorked);

            writer.WriteNumber("JobId", wDEntry.JobId);

            writer.WriteString("Location", wDEntry.Location);

            writer.WriteString("MilesDriven", wDEntry.MilesDriven);

            writer.WriteString("TrueHoursWorked", wDEntry.TrueHoursWorked);

            writer.WriteNumber("WorkerId", wDEntry.WorkerId);
        }
    }
}
