// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// A worker&#39;s admin-visible profile, safe to expose over the JSON API - unlike [&#x60;Worker&#x60;], this deliberately excludes &#x60;hash&#x60;/&#x60;salt&#x60;.  This is the shape used both by &#x60;/admin/api/v1/users&#x60; (worker management) and, filtered to active workers, by job-assignment flows that just need to know who exists and pick some subset of them.
    /// </summary>
    public partial class WorkerSummary : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkerSummary" /> class.
        /// </summary>
        /// <param name="address">address</param>
        /// <param name="admin">admin</param>
        /// <param name="deactivated">deactivated</param>
        /// <param name="email">email</param>
        /// <param name="flatRateCents">flatRateCents</param>
        /// <param name="id">id</param>
        /// <param name="mustChangePw">mustChangePw</param>
        /// <param name="name">name</param>
        /// <param name="phone">phone</param>
        /// <param name="rateDriveHourlyCents">rateDriveHourlyCents</param>
        /// <param name="rateHourlyCents">rateHourlyCents</param>
        /// <param name="rateMileageCents">rateMileageCents</param>
        [JsonConstructor]
        public WorkerSummary(string address, bool admin, bool deactivated, string email, long flatRateCents, long id, bool mustChangePw, string name, string phone, long rateDriveHourlyCents, long rateHourlyCents, long rateMileageCents)
        {
            Address = address;
            Admin = admin;
            Deactivated = deactivated;
            Email = email;
            FlatRateCents = flatRateCents;
            Id = id;
            MustChangePw = mustChangePw;
            Name = name;
            Phone = phone;
            RateDriveHourlyCents = rateDriveHourlyCents;
            RateHourlyCents = rateHourlyCents;
            RateMileageCents = rateMileageCents;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [JsonPropertyName("address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or Sets Admin
        /// </summary>
        [JsonPropertyName("admin")]
        public bool Admin { get; set; }

        /// <summary>
        /// Gets or Sets Deactivated
        /// </summary>
        [JsonPropertyName("deactivated")]
        public bool Deactivated { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets FlatRateCents
        /// </summary>
        [JsonPropertyName("flat_rate_cents")]
        public long FlatRateCents { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public long Id { get; set; }

        /// <summary>
        /// Gets or Sets MustChangePw
        /// </summary>
        [JsonPropertyName("must_change_pw")]
        public bool MustChangePw { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Phone
        /// </summary>
        [JsonPropertyName("phone")]
        public string Phone { get; set; }

        /// <summary>
        /// Gets or Sets RateDriveHourlyCents
        /// </summary>
        [JsonPropertyName("rate_drive_hourly_cents")]
        public long RateDriveHourlyCents { get; set; }

        /// <summary>
        /// Gets or Sets RateHourlyCents
        /// </summary>
        [JsonPropertyName("rate_hourly_cents")]
        public long RateHourlyCents { get; set; }

        /// <summary>
        /// Gets or Sets RateMileageCents
        /// </summary>
        [JsonPropertyName("rate_mileage_cents")]
        public long RateMileageCents { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkerSummary {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Admin: ").Append(Admin).Append("\n");
            sb.Append("  Deactivated: ").Append(Deactivated).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  FlatRateCents: ").Append(FlatRateCents).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  MustChangePw: ").Append(MustChangePw).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  RateDriveHourlyCents: ").Append(RateDriveHourlyCents).Append("\n");
            sb.Append("  RateHourlyCents: ").Append(RateHourlyCents).Append("\n");
            sb.Append("  RateMileageCents: ").Append(RateMileageCents).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WorkerSummary" />
    /// </summary>
    public class WorkerSummaryJsonConverter : JsonConverter<WorkerSummary>
    {
        /// <summary>
        /// Deserializes json to <see cref="WorkerSummary" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WorkerSummary Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> address = default;
            Option<bool?> admin = default;
            Option<bool?> deactivated = default;
            Option<string?> email = default;
            Option<long?> flatRateCents = default;
            Option<long?> id = default;
            Option<bool?> mustChangePw = default;
            Option<string?> name = default;
            Option<string?> phone = default;
            Option<long?> rateDriveHourlyCents = default;
            Option<long?> rateHourlyCents = default;
            Option<long?> rateMileageCents = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "address":
                            address = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "admin":
                            admin = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "deactivated":
                            deactivated = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "flat_rate_cents":
                            flatRateCents = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "id":
                            id = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "must_change_pw":
                            mustChangePw = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "phone":
                            phone = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "rate_drive_hourly_cents":
                            rateDriveHourlyCents = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "rate_hourly_cents":
                            rateHourlyCents = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "rate_mileage_cents":
                            rateMileageCents = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!address.IsSet)
                throw new ArgumentException("Property is required for class WorkerSummary.", nameof(address));

            if (!admin.IsSet)
                throw new ArgumentException("Property is required for class WorkerSummary.", nameof(admin));

            if (!deactivated.IsSet)
                throw new ArgumentException("Property is required for class WorkerSummary.", nameof(deactivated));

            if (!email.IsSet)
                throw new ArgumentException("Property is required for class WorkerSummary.", nameof(email));

            if (!flatRateCents.IsSet)
                throw new ArgumentException("Property is required for class WorkerSummary.", nameof(flatRateCents));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class WorkerSummary.", nameof(id));

            if (!mustChangePw.IsSet)
                throw new ArgumentException("Property is required for class WorkerSummary.", nameof(mustChangePw));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class WorkerSummary.", nameof(name));

            if (!phone.IsSet)
                throw new ArgumentException("Property is required for class WorkerSummary.", nameof(phone));

            if (!rateDriveHourlyCents.IsSet)
                throw new ArgumentException("Property is required for class WorkerSummary.", nameof(rateDriveHourlyCents));

            if (!rateHourlyCents.IsSet)
                throw new ArgumentException("Property is required for class WorkerSummary.", nameof(rateHourlyCents));

            if (!rateMileageCents.IsSet)
                throw new ArgumentException("Property is required for class WorkerSummary.", nameof(rateMileageCents));

            if (address.IsSet && address.Value == null)
                throw new ArgumentNullException(nameof(address), "Property is not nullable for class WorkerSummary.");

            if (admin.IsSet && admin.Value == null)
                throw new ArgumentNullException(nameof(admin), "Property is not nullable for class WorkerSummary.");

            if (deactivated.IsSet && deactivated.Value == null)
                throw new ArgumentNullException(nameof(deactivated), "Property is not nullable for class WorkerSummary.");

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class WorkerSummary.");

            if (flatRateCents.IsSet && flatRateCents.Value == null)
                throw new ArgumentNullException(nameof(flatRateCents), "Property is not nullable for class WorkerSummary.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class WorkerSummary.");

            if (mustChangePw.IsSet && mustChangePw.Value == null)
                throw new ArgumentNullException(nameof(mustChangePw), "Property is not nullable for class WorkerSummary.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class WorkerSummary.");

            if (phone.IsSet && phone.Value == null)
                throw new ArgumentNullException(nameof(phone), "Property is not nullable for class WorkerSummary.");

            if (rateDriveHourlyCents.IsSet && rateDriveHourlyCents.Value == null)
                throw new ArgumentNullException(nameof(rateDriveHourlyCents), "Property is not nullable for class WorkerSummary.");

            if (rateHourlyCents.IsSet && rateHourlyCents.Value == null)
                throw new ArgumentNullException(nameof(rateHourlyCents), "Property is not nullable for class WorkerSummary.");

            if (rateMileageCents.IsSet && rateMileageCents.Value == null)
                throw new ArgumentNullException(nameof(rateMileageCents), "Property is not nullable for class WorkerSummary.");

            return new WorkerSummary(address.Value!, admin.Value!.Value!, deactivated.Value!.Value!, email.Value!, flatRateCents.Value!.Value!, id.Value!.Value!, mustChangePw.Value!.Value!, name.Value!, phone.Value!, rateDriveHourlyCents.Value!.Value!, rateHourlyCents.Value!.Value!, rateMileageCents.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="WorkerSummary" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="workerSummary"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WorkerSummary workerSummary, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, workerSummary, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WorkerSummary" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="workerSummary"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WorkerSummary workerSummary, JsonSerializerOptions jsonSerializerOptions)
        {
            if (workerSummary.Address == null)
                throw new ArgumentNullException(nameof(workerSummary.Address), "Property is required for class WorkerSummary.");

            if (workerSummary.Email == null)
                throw new ArgumentNullException(nameof(workerSummary.Email), "Property is required for class WorkerSummary.");

            if (workerSummary.Name == null)
                throw new ArgumentNullException(nameof(workerSummary.Name), "Property is required for class WorkerSummary.");

            if (workerSummary.Phone == null)
                throw new ArgumentNullException(nameof(workerSummary.Phone), "Property is required for class WorkerSummary.");

            writer.WriteString("address", workerSummary.Address);

            writer.WriteBoolean("admin", workerSummary.Admin);

            writer.WriteBoolean("deactivated", workerSummary.Deactivated);

            writer.WriteString("email", workerSummary.Email);

            writer.WriteNumber("flat_rate_cents", workerSummary.FlatRateCents);

            writer.WriteNumber("id", workerSummary.Id);

            writer.WriteBoolean("must_change_pw", workerSummary.MustChangePw);

            writer.WriteString("name", workerSummary.Name);

            writer.WriteString("phone", workerSummary.Phone);

            writer.WriteNumber("rate_drive_hourly_cents", workerSummary.RateDriveHourlyCents);

            writer.WriteNumber("rate_hourly_cents", workerSummary.RateHourlyCents);

            writer.WriteNumber("rate_mileage_cents", workerSummary.RateMileageCents);
        }
    }
}
