// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// WorkerDataOutput
    /// </summary>
    public partial class WorkerDataOutput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkerDataOutput" /> class.
        /// </summary>
        /// <param name="entries">entries</param>
        /// <param name="from">from</param>
        /// <param name="numJobs">numJobs</param>
        /// <param name="to">to</param>
        /// <param name="totals">totals</param>
        [JsonConstructor]
        public WorkerDataOutput(List<WDEntry> entries, string from, int numJobs, string to, WDEntry totals)
        {
            Entries = entries;
            From = from;
            NumJobs = numJobs;
            To = to;
            Totals = totals;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Entries
        /// </summary>
        [JsonPropertyName("entries")]
        public List<WDEntry> Entries { get; set; }

        /// <summary>
        /// Gets or Sets From
        /// </summary>
        [JsonPropertyName("from")]
        public string From { get; set; }

        /// <summary>
        /// Gets or Sets NumJobs
        /// </summary>
        [JsonPropertyName("num_jobs")]
        public int NumJobs { get; set; }

        /// <summary>
        /// Gets or Sets To
        /// </summary>
        [JsonPropertyName("to")]
        public string To { get; set; }

        /// <summary>
        /// Gets or Sets Totals
        /// </summary>
        [JsonPropertyName("totals")]
        public WDEntry Totals { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkerDataOutput {\n");
            sb.Append("  Entries: ").Append(Entries).Append("\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  NumJobs: ").Append(NumJobs).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  Totals: ").Append(Totals).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // NumJobs (int) minimum
            if (this.NumJobs < (int)0)
            {
                yield return new ValidationResult("Invalid value for NumJobs, must be a value greater than or equal to 0.", new [] { "NumJobs" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WorkerDataOutput" />
    /// </summary>
    public class WorkerDataOutputJsonConverter : JsonConverter<WorkerDataOutput>
    {
        /// <summary>
        /// Deserializes json to <see cref="WorkerDataOutput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WorkerDataOutput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<WDEntry>?> entries = default;
            Option<string?> from = default;
            Option<int?> numJobs = default;
            Option<string?> to = default;
            Option<WDEntry?> totals = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "entries":
                            entries = new Option<List<WDEntry>?>(JsonSerializer.Deserialize<List<WDEntry>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "from":
                            from = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "num_jobs":
                            numJobs = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "to":
                            to = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "totals":
                            totals = new Option<WDEntry?>(JsonSerializer.Deserialize<WDEntry>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!entries.IsSet)
                throw new ArgumentException("Property is required for class WorkerDataOutput.", nameof(entries));

            if (!from.IsSet)
                throw new ArgumentException("Property is required for class WorkerDataOutput.", nameof(from));

            if (!numJobs.IsSet)
                throw new ArgumentException("Property is required for class WorkerDataOutput.", nameof(numJobs));

            if (!to.IsSet)
                throw new ArgumentException("Property is required for class WorkerDataOutput.", nameof(to));

            if (!totals.IsSet)
                throw new ArgumentException("Property is required for class WorkerDataOutput.", nameof(totals));

            if (entries.IsSet && entries.Value == null)
                throw new ArgumentNullException(nameof(entries), "Property is not nullable for class WorkerDataOutput.");

            if (from.IsSet && from.Value == null)
                throw new ArgumentNullException(nameof(from), "Property is not nullable for class WorkerDataOutput.");

            if (numJobs.IsSet && numJobs.Value == null)
                throw new ArgumentNullException(nameof(numJobs), "Property is not nullable for class WorkerDataOutput.");

            if (to.IsSet && to.Value == null)
                throw new ArgumentNullException(nameof(to), "Property is not nullable for class WorkerDataOutput.");

            if (totals.IsSet && totals.Value == null)
                throw new ArgumentNullException(nameof(totals), "Property is not nullable for class WorkerDataOutput.");

            return new WorkerDataOutput(entries.Value!, from.Value!, numJobs.Value!.Value!, to.Value!, totals.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="WorkerDataOutput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="workerDataOutput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WorkerDataOutput workerDataOutput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, workerDataOutput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WorkerDataOutput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="workerDataOutput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WorkerDataOutput workerDataOutput, JsonSerializerOptions jsonSerializerOptions)
        {
            if (workerDataOutput.Entries == null)
                throw new ArgumentNullException(nameof(workerDataOutput.Entries), "Property is required for class WorkerDataOutput.");

            if (workerDataOutput.From == null)
                throw new ArgumentNullException(nameof(workerDataOutput.From), "Property is required for class WorkerDataOutput.");

            if (workerDataOutput.To == null)
                throw new ArgumentNullException(nameof(workerDataOutput.To), "Property is required for class WorkerDataOutput.");

            if (workerDataOutput.Totals == null)
                throw new ArgumentNullException(nameof(workerDataOutput.Totals), "Property is required for class WorkerDataOutput.");

            writer.WritePropertyName("entries");
            JsonSerializer.Serialize(writer, workerDataOutput.Entries, jsonSerializerOptions);
            writer.WriteString("from", workerDataOutput.From);

            writer.WriteNumber("num_jobs", workerDataOutput.NumJobs);

            writer.WriteString("to", workerDataOutput.To);

            writer.WritePropertyName("totals");
            JsonSerializer.Serialize(writer, workerDataOutput.Totals, jsonSerializerOptions);
        }
    }
}
