// <auto-generated>
/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Request body shared by the web form and the JSON API for creating a worker. Money fields are decimal strings (e.g. &#x60;\&quot;12.50\&quot;&#x60;), matching what the HTML form sends; the JSON API accepts the same convention for consistency between the two.
    /// </summary>
    public partial class WorkerCreateInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkerCreateInput" /> class.
        /// </summary>
        /// <param name="address">address</param>
        /// <param name="drivetime">drivetime</param>
        /// <param name="email">email</param>
        /// <param name="flatrate">flatrate</param>
        /// <param name="hourly">hourly</param>
        /// <param name="mileage">mileage</param>
        /// <param name="name">name</param>
        /// <param name="phone">phone</param>
        /// <param name="admin">admin</param>
        [JsonConstructor]
        public WorkerCreateInput(string address, string drivetime, string email, string flatrate, string hourly, string mileage, string name, string phone, Option<bool?> admin = default)
        {
            Address = address;
            Drivetime = drivetime;
            Email = email;
            Flatrate = flatrate;
            Hourly = hourly;
            Mileage = mileage;
            Name = name;
            Phone = phone;
            AdminOption = admin;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [JsonPropertyName("address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or Sets Drivetime
        /// </summary>
        [JsonPropertyName("drivetime")]
        public string Drivetime { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Flatrate
        /// </summary>
        [JsonPropertyName("flatrate")]
        public string Flatrate { get; set; }

        /// <summary>
        /// Gets or Sets Hourly
        /// </summary>
        [JsonPropertyName("hourly")]
        public string Hourly { get; set; }

        /// <summary>
        /// Gets or Sets Mileage
        /// </summary>
        [JsonPropertyName("mileage")]
        public string Mileage { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Phone
        /// </summary>
        [JsonPropertyName("phone")]
        public string Phone { get; set; }

        /// <summary>
        /// Used to track the state of Admin
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AdminOption { get; private set; }

        /// <summary>
        /// Gets or Sets Admin
        /// </summary>
        [JsonPropertyName("admin")]
        public bool? Admin { get { return this.AdminOption.Value; } set { this.AdminOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkerCreateInput {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Drivetime: ").Append(Drivetime).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Flatrate: ").Append(Flatrate).Append("\n");
            sb.Append("  Hourly: ").Append(Hourly).Append("\n");
            sb.Append("  Mileage: ").Append(Mileage).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  Admin: ").Append(Admin).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WorkerCreateInput" />
    /// </summary>
    public class WorkerCreateInputJsonConverter : JsonConverter<WorkerCreateInput>
    {
        /// <summary>
        /// Deserializes json to <see cref="WorkerCreateInput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WorkerCreateInput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> address = default;
            Option<string?> drivetime = default;
            Option<string?> email = default;
            Option<string?> flatrate = default;
            Option<string?> hourly = default;
            Option<string?> mileage = default;
            Option<string?> name = default;
            Option<string?> phone = default;
            Option<bool?> admin = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "address":
                            address = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "drivetime":
                            drivetime = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "flatrate":
                            flatrate = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "hourly":
                            hourly = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "mileage":
                            mileage = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "phone":
                            phone = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "admin":
                            admin = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!address.IsSet)
                throw new ArgumentException("Property is required for class WorkerCreateInput.", nameof(address));

            if (!drivetime.IsSet)
                throw new ArgumentException("Property is required for class WorkerCreateInput.", nameof(drivetime));

            if (!email.IsSet)
                throw new ArgumentException("Property is required for class WorkerCreateInput.", nameof(email));

            if (!flatrate.IsSet)
                throw new ArgumentException("Property is required for class WorkerCreateInput.", nameof(flatrate));

            if (!hourly.IsSet)
                throw new ArgumentException("Property is required for class WorkerCreateInput.", nameof(hourly));

            if (!mileage.IsSet)
                throw new ArgumentException("Property is required for class WorkerCreateInput.", nameof(mileage));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class WorkerCreateInput.", nameof(name));

            if (!phone.IsSet)
                throw new ArgumentException("Property is required for class WorkerCreateInput.", nameof(phone));

            if (address.IsSet && address.Value == null)
                throw new ArgumentNullException(nameof(address), "Property is not nullable for class WorkerCreateInput.");

            if (drivetime.IsSet && drivetime.Value == null)
                throw new ArgumentNullException(nameof(drivetime), "Property is not nullable for class WorkerCreateInput.");

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class WorkerCreateInput.");

            if (flatrate.IsSet && flatrate.Value == null)
                throw new ArgumentNullException(nameof(flatrate), "Property is not nullable for class WorkerCreateInput.");

            if (hourly.IsSet && hourly.Value == null)
                throw new ArgumentNullException(nameof(hourly), "Property is not nullable for class WorkerCreateInput.");

            if (mileage.IsSet && mileage.Value == null)
                throw new ArgumentNullException(nameof(mileage), "Property is not nullable for class WorkerCreateInput.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class WorkerCreateInput.");

            if (phone.IsSet && phone.Value == null)
                throw new ArgumentNullException(nameof(phone), "Property is not nullable for class WorkerCreateInput.");

            return new WorkerCreateInput(address.Value!, drivetime.Value!, email.Value!, flatrate.Value!, hourly.Value!, mileage.Value!, name.Value!, phone.Value!, admin);
        }

        /// <summary>
        /// Serializes a <see cref="WorkerCreateInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="workerCreateInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WorkerCreateInput workerCreateInput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, workerCreateInput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WorkerCreateInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="workerCreateInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WorkerCreateInput workerCreateInput, JsonSerializerOptions jsonSerializerOptions)
        {
            if (workerCreateInput.Address == null)
                throw new ArgumentNullException(nameof(workerCreateInput.Address), "Property is required for class WorkerCreateInput.");

            if (workerCreateInput.Drivetime == null)
                throw new ArgumentNullException(nameof(workerCreateInput.Drivetime), "Property is required for class WorkerCreateInput.");

            if (workerCreateInput.Email == null)
                throw new ArgumentNullException(nameof(workerCreateInput.Email), "Property is required for class WorkerCreateInput.");

            if (workerCreateInput.Flatrate == null)
                throw new ArgumentNullException(nameof(workerCreateInput.Flatrate), "Property is required for class WorkerCreateInput.");

            if (workerCreateInput.Hourly == null)
                throw new ArgumentNullException(nameof(workerCreateInput.Hourly), "Property is required for class WorkerCreateInput.");

            if (workerCreateInput.Mileage == null)
                throw new ArgumentNullException(nameof(workerCreateInput.Mileage), "Property is required for class WorkerCreateInput.");

            if (workerCreateInput.Name == null)
                throw new ArgumentNullException(nameof(workerCreateInput.Name), "Property is required for class WorkerCreateInput.");

            if (workerCreateInput.Phone == null)
                throw new ArgumentNullException(nameof(workerCreateInput.Phone), "Property is required for class WorkerCreateInput.");

            writer.WriteString("address", workerCreateInput.Address);

            writer.WriteString("drivetime", workerCreateInput.Drivetime);

            writer.WriteString("email", workerCreateInput.Email);

            writer.WriteString("flatrate", workerCreateInput.Flatrate);

            writer.WriteString("hourly", workerCreateInput.Hourly);

            writer.WriteString("mileage", workerCreateInput.Mileage);

            writer.WriteString("name", workerCreateInput.Name);

            writer.WriteString("phone", workerCreateInput.Phone);

            if (workerCreateInput.AdminOption.IsSet)
                if (workerCreateInput.AdminOption.Value != null)
                    writer.WriteBoolean("admin", workerCreateInput.AdminOption.Value!.Value);
                else
                    writer.WriteNull("admin");
        }
    }
}
