/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing AdminApi
    /// </summary>
    public sealed class AdminApiTests : ApiTestsBase
    {
        private readonly IAdminApi _instance;

        public AdminApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IAdminApi>();
        }

        /// <summary>
        /// Test ChangeWorkerApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ChangeWorkerApiAsyncTest()
        {
            WorkerChangeInput workerChangeInput = default!;
            var response = await _instance.ChangeWorkerApiAsync(workerChangeInput);
            var model = response.Ok();
            Assert.IsType<WorkerChangeOutput>(model);
        }

        /// <summary>
        /// Test CreateJobApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateJobApiAsyncTest()
        {
            JobEditInput jobEditInput = default!;
            var response = await _instance.CreateJobApiAsync(jobEditInput);
            var model = response.Created();
            Assert.IsType<JobEditOutput>(model);
        }

        /// <summary>
        /// Test CreateWorkerApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateWorkerApiAsyncTest()
        {
            WorkerCreateInput workerCreateInput = default!;
            var response = await _instance.CreateWorkerApiAsync(workerCreateInput);
            var model = response.Created();
            Assert.IsType<WorkerCreateOutput>(model);
        }

        /// <summary>
        /// Test DeactivateApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeactivateApiAsyncTest()
        {
            DeactivateInput deactivateInput = default!;
            var response = await _instance.DeactivateApiAsync(deactivateInput);
            var model = response.Ok();
            Assert.IsType<DeactivateOutput>(model);
        }

        /// <summary>
        /// Test DeleteJobApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteJobApiAsyncTest()
        {
            long id = default!;
            var response = await _instance.DeleteJobApiAsync(id);
            var model = response.Ok();
            Assert.IsType<JobDeleteOutput>(model);
        }

        /// <summary>
        /// Test ExportDb
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ExportDbAsyncTest()
        {
            await _instance.ExportDbAsync();
        }

        /// <summary>
        /// Test GetUserApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetUserApiAsyncTest()
        {
            long id = default!;
            var response = await _instance.GetUserApiAsync(id);
            var model = response.Ok();
            Assert.IsType<WorkerSummary>(model);
        }

        /// <summary>
        /// Test JobeditpageApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task JobeditpageApiAsyncTest()
        {
            long id = default!;
            var response = await _instance.JobeditpageApiAsync(id);
            var model = response.Ok();
            Assert.IsType<JobEditPageOutput>(model);
        }

        /// <summary>
        /// Test ListUsersApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListUsersApiAsyncTest()
        {
            var response = await _instance.ListUsersApiAsync();
            var model = response.Ok();
            Assert.IsType<List<WorkerSummary>>(model);
        }

        /// <summary>
        /// Test LogoutUserApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task LogoutUserApiAsyncTest()
        {
            LogoutForm logoutForm = default!;
            var response = await _instance.LogoutUserApiAsync(logoutForm);
            var model = response.Ok();
            Assert.IsType<LogoutUserOutput>(model);
        }

        /// <summary>
        /// Test ResetPwApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ResetPwApiAsyncTest()
        {
            ResetPwInput resetPwInput = default!;
            var response = await _instance.ResetPwApiAsync(resetPwInput);
            var model = response.Ok();
            Assert.IsType<ResetPwOutput>(model);
        }

        /// <summary>
        /// Test RestoreApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RestoreApiAsyncTest()
        {
            RestoreInput restoreInput = default!;
            var response = await _instance.RestoreApiAsync(restoreInput);
            var model = response.Ok();
            Assert.IsType<RestoreOutput>(model);
        }

        /// <summary>
        /// Test UpdateJobApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateJobApiAsyncTest()
        {
            long id = default!;
            JobEditInput jobEditInput = default!;
            var response = await _instance.UpdateJobApiAsync(id, jobEditInput);
            var model = response.Ok();
            Assert.IsType<JobEditOutput>(model);
        }
    }
}
