/*
 * CZ4R API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing UserApi
    /// </summary>
    public sealed class UserApiTests : ApiTestsBase
    {
        private readonly IUserApi _instance;

        public UserApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IUserApi>();
        }

        /// <summary>
        /// Test AssignmentDataApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AssignmentDataApiAsyncTest()
        {
            long id = default!;
            long worker = default!;
            var response = await _instance.AssignmentDataApiAsync(id, worker);
            var model = response.Ok();
            Assert.IsType<FullAssignmentData>(model);
        }

        /// <summary>
        /// Test ChangePwApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ChangePwApiAsyncTest()
        {
            ChangePwInput changePwInput = default!;
            var response = await _instance.ChangePwApiAsync(changePwInput);
            var model = response.Ok();
            Assert.IsType<ChangePwOutput>(model);
        }

        /// <summary>
        /// Test CheckinoutApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CheckinoutApiAsyncTest()
        {
            CheckInOutInput checkInOutInput = default!;
            var response = await _instance.CheckinoutApiAsync(checkInOutInput);
            var model = response.Ok();
            Assert.IsType<CheckInOutOutput>(model);
        }

        /// <summary>
        /// Test IndexApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task IndexApiAsyncTest()
        {
            var response = await _instance.IndexApiAsync();
            var model = response.Ok();
            Assert.IsType<HomeStats>(model);
        }

        /// <summary>
        /// Test JoblistApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task JoblistApiAsyncTest()
        {
            Client.Option<DateOnly?> startDate = default!;
            Client.Option<DateOnly?> endDate = default!;
            Client.Option<string?> siteName = default!;
            Client.Option<string?> workOrder = default!;
            Client.Option<string?> address = default!;
            Client.Option<string?> notes = default!;
            Client.Option<Order?> order = default!;
            Client.Option<bool?> assigned = default!;
            Client.Option<bool?> started = default!;
            Client.Option<bool?> completed = default!;
            Client.Option<string?> workers = default!;
            var response = await _instance.JoblistApiAsync(startDate, endDate, siteName, workOrder, address, notes, order, assigned, started, completed, workers);
            var model = response.Ok();
            Assert.IsType<JobListOutput>(model);
        }

        /// <summary>
        /// Test LoginApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task LoginApiAsyncTest()
        {
            LoginForm loginForm = default!;
            var response = await _instance.LoginApiAsync(loginForm);
            var model = response.Ok();
            Assert.IsType<LoginOutput>(model);
        }

        /// <summary>
        /// Test LogoutApi
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task LogoutApiAsyncTest()
        {
            var response = await _instance.LogoutApiAsync();
            var model = response.Ok();
            Assert.IsType<LogoutOutput>(model);
        }

        /// <summary>
        /// Test Whoami
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task WhoamiAsyncTest()
        {
            var response = await _instance.WhoamiAsync();
            var model = response.Ok();
            Assert.IsType<WorkerSummary>(model);
        }
    }
}
